#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import httpclient
import json
import logging
import marshal
import options
import strformat
import strutils
import tables
import typetraits
import uri

import ../models/model_add_domain_config_params
import ../models/model_add_domain_config_response
import ../models/model_add_hash_tag_response
import ../models/model_add_hash_tags_bulk_response
import ../models/model_add_page_api_response
import ../models/model_add_sso_user_api_response
import ../models/model_aggregate_question_results_response1
import ../models/model_aggregate_response
import ../models/model_aggregate_time_bucket
import ../models/model_aggregation_request
import ../models/model_block_from_comment_params
import ../models/model_block_user_from_comment_response
import ../models/model_bulk_aggregate_question_results_request
import ../models/model_bulk_aggregate_question_results_response1
import ../models/model_bulk_create_hash_tags_body
import ../models/model_change_ticket_state_body
import ../models/model_change_ticket_state_response1
import ../models/model_combine_comments_with_question_results_response
import ../models/model_create_api_page_data
import ../models/model_create_apisso_user_data
import ../models/model_create_api_user_subscription_data
import ../models/model_create_comment_params
import ../models/model_create_email_template_body
import ../models/model_create_email_template_response1
import ../models/model_create_feed_post_params
import ../models/model_create_feed_post_response1
import ../models/model_create_hash_tag_body
import ../models/model_create_moderator_body
import ../models/model_create_moderator_response1
import ../models/model_create_question_config_body
import ../models/model_create_question_config_response1
import ../models/model_create_question_result_body
import ../models/model_create_question_result_response1
import ../models/model_create_subscription_api_response
import ../models/model_create_tenant_body
import ../models/model_create_tenant_package_body
import ../models/model_create_tenant_package_response1
import ../models/model_create_tenant_response1
import ../models/model_create_tenant_user_body
import ../models/model_create_tenant_user_response1
import ../models/model_create_ticket_body
import ../models/model_create_ticket_response1
import ../models/model_create_user_badge_params
import ../models/model_create_user_badge_response
import ../models/model_create_vote_response
import ../models/model_delete_comment_response
import ../models/model_delete_domain_config_response
import ../models/model_delete_email_template_render_error_response
import ../models/model_delete_email_template_response
import ../models/model_delete_hash_tag_request_body
import ../models/model_delete_hash_tag_response
import ../models/model_delete_moderator_response
import ../models/model_delete_notification_count_response
import ../models/model_delete_page_api_response
import ../models/model_delete_pending_webhook_event_response
import ../models/model_delete_question_config_response
import ../models/model_delete_question_result_response
import ../models/model_delete_sso_user_api_response
import ../models/model_delete_subscription_api_response
import ../models/model_delete_tenant_package_response
import ../models/model_delete_tenant_response
import ../models/model_delete_tenant_user_response
import ../models/model_delete_user_badge_response
import ../models/model_delete_vote_response
import ../models/model_feed_post
import ../models/model_flag_comment_response1
import ../models/model_get_audit_logs_response1
import ../models/model_get_cached_notification_count_response1
import ../models/model_get_comment_response
import ../models/model_get_comments_response
import ../models/model_get_domain_config_response
import ../models/model_get_domain_configs_response
import ../models/model_get_email_template_definitions_response1
import ../models/model_get_email_template_render_errors_response1
import ../models/model_get_email_template_response1
import ../models/model_get_email_templates_response1
import ../models/model_get_feed_posts_response1
import ../models/model_get_hash_tags_response1
import ../models/model_get_moderator_response1
import ../models/model_get_moderators_response1
import ../models/model_get_notification_count_response1
import ../models/model_get_notifications_response1
import ../models/model_get_page_by_urlid_api_response
import ../models/model_get_pages_api_response
import ../models/model_get_pending_webhook_event_count_response1
import ../models/model_get_pending_webhook_events_response1
import ../models/model_get_question_config_response1
import ../models/model_get_question_configs_response1
import ../models/model_get_question_result_response1
import ../models/model_get_question_results_response1
import ../models/model_get_sso_user_by_email_api_response
import ../models/model_get_sso_user_by_id_api_response
import ../models/model_get_sso_users_response
import ../models/model_get_subscriptions_api_response
import ../models/model_get_tenant_daily_usages_response1
import ../models/model_get_tenant_package_response1
import ../models/model_get_tenant_packages_response1
import ../models/model_get_tenant_response1
import ../models/model_get_tenant_user_response1
import ../models/model_get_tenant_users_response1
import ../models/model_get_tenants_response1
import ../models/model_get_ticket_response1
import ../models/model_get_tickets_response1
import ../models/model_get_user_badge_progress_by_id_response
import ../models/model_get_user_badge_progress_by_user_id_response
import ../models/model_get_user_badge_progress_list_response
import ../models/model_get_user_badge_response
import ../models/model_get_user_badges_response
import ../models/model_get_user_response1
import ../models/model_get_votes_for_user_response1
import ../models/model_get_votes_response1
import ../models/model_patch_domain_config_params
import ../models/model_patch_domain_config_response
import ../models/model_patch_hash_tag_response
import ../models/model_patch_page_api_response
import ../models/model_patch_sso_user_api_response
import ../models/model_put_domain_config_response
import ../models/model_put_sso_user_api_response
import ../models/model_render_email_template_body
import ../models/model_render_email_template_response1
import ../models/model_replace_tenant_package_body
import ../models/model_replace_tenant_package_response
import ../models/model_replace_tenant_user_body
import ../models/model_replace_tenant_user_response
import ../models/model_sort_dir
import ../models/model_save_comment_response
import ../models/model_save_comments_bulk_response
import ../models/model_send_invite_response
import ../models/model_send_login_link_response
import ../models/model_sort_directions
import ../models/model_un_block_from_comment_params
import ../models/model_un_block_user_from_comment_response
import ../models/model_un_flag_comment_response
import ../models/model_updatable_comment_params
import ../models/model_update_api_page_data
import ../models/model_update_apisso_user_data
import ../models/model_update_api_user_subscription_data
import ../models/model_update_comment_response
import ../models/model_update_domain_config_params
import ../models/model_update_email_template_body
import ../models/model_update_email_template_response
import ../models/model_update_feed_post_response
import ../models/model_update_hash_tag_body
import ../models/model_update_moderator_body
import ../models/model_update_moderator_response
import ../models/model_update_notification_body
import ../models/model_update_notification_response
import ../models/model_update_question_config_body
import ../models/model_update_question_config_response
import ../models/model_update_question_result_body
import ../models/model_update_question_result_response
import ../models/model_update_subscription_api_response
import ../models/model_update_tenant_body
import ../models/model_update_tenant_package_body
import ../models/model_update_tenant_package_response
import ../models/model_update_tenant_response
import ../models/model_update_tenant_user_body
import ../models/model_update_tenant_user_response
import ../models/model_update_user_badge_params
import ../models/model_update_user_badge_response

const basepath = "https://fastcomments.com"

template constructResult[T](response: Response): untyped =
  if response.code in {Http200, Http201, Http202, Http204, Http206}:
    try:
      (some(to(parseJson(response.body), T)), response)
    except JsonParsingError:
      # The server returned a malformed response though the response code is 2XX
      # TODO: need better error handling
      error("JsonParsingError")
      (none(T.typedesc), response)
  else:
    (none(T.typedesc), response)


proc addDomainConfig*(httpClient: HttpClient, tenantId: string, addDomainConfigParams: AddDomainConfigParams): (Option[AddDomainConfigResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/domain-configs" & "?" & url_encoded_query_params, $(%addDomainConfigParams))
  constructResult[AddDomainConfigResponse](response)


proc addHashTag*(httpClient: HttpClient, tenantId: string, createHashTagBody: CreateHashTagBody): (Option[AddHashTagResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  if $tenantId != "":
    query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/hash-tags" & "?" & url_encoded_query_params, $(%createHashTagBody))
  constructResult[AddHashTagResponse](response)


proc addHashTagsBulk*(httpClient: HttpClient, tenantId: string, bulkCreateHashTagsBody: BulkCreateHashTagsBody): (Option[AddHashTagsBulkResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  if $tenantId != "":
    query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/hash-tags/bulk" & "?" & url_encoded_query_params, $(%bulkCreateHashTagsBody))
  constructResult[AddHashTagsBulkResponse](response)


proc addPage*(httpClient: HttpClient, tenantId: string, createAPIPageData: CreateAPIPageData): (Option[AddPageAPIResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/pages" & "?" & url_encoded_query_params, $(%createAPIPageData))
  constructResult[AddPageAPIResponse](response)


proc addSSOUser*(httpClient: HttpClient, tenantId: string, createAPISSOUserData: CreateAPISSOUserData): (Option[AddSSOUserAPIResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/sso-users" & "?" & url_encoded_query_params, $(%createAPISSOUserData))
  constructResult[AddSSOUserAPIResponse](response)


proc aggregate*(httpClient: HttpClient, tenantId: string, aggregationRequest: AggregationRequest, parentTenantId: string, includeStats: bool): (Option[AggregateResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $parentTenantId != "":
    query_params_list.add(("parentTenantId", $parentTenantId))
  if $includeStats != "":
    query_params_list.add(("includeStats", $includeStats))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/aggregate" & "?" & url_encoded_query_params, $(%aggregationRequest))
  constructResult[AggregateResponse](response)


proc aggregateQuestionResults*(httpClient: HttpClient, tenantId: string, questionId: string, questionIds: seq[string], urlId: string, timeBucket: AggregateTimeBucket, startDate: string, forceRecalculate: bool): (Option[AggregateQuestionResultsResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $questionId != "":
    query_params_list.add(("questionId", $questionId))
  if questionIds.len > 0:
    query_params_list.add(("questionIds", $questionIds.join(",")))
  if $urlId != "":
    query_params_list.add(("urlId", $urlId))
  if $timeBucket != "":
    query_params_list.add(("timeBucket", $timeBucket))
  if $startDate != "":
    query_params_list.add(("startDate", $startDate))
  if $forceRecalculate != "":
    query_params_list.add(("forceRecalculate", $forceRecalculate))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/question-results-aggregation" & "?" & url_encoded_query_params)
  constructResult[AggregateQuestionResultsResponse1](response)


proc blockUserFromComment*(httpClient: HttpClient, tenantId: string, id: string, blockFromCommentParams: BlockFromCommentParams, userId: string, anonUserId: string): (Option[BlockUserFromCommentResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  if $anonUserId != "":
    query_params_list.add(("anonUserId", $anonUserId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & fmt"/api/v1/comments/{id}/block" & "?" & url_encoded_query_params, $(%blockFromCommentParams))
  constructResult[BlockUserFromCommentResponse](response)


proc bulkAggregateQuestionResults*(httpClient: HttpClient, tenantId: string, bulkAggregateQuestionResultsRequest: BulkAggregateQuestionResultsRequest, forceRecalculate: bool): (Option[BulkAggregateQuestionResultsResponse1], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $forceRecalculate != "":
    query_params_list.add(("forceRecalculate", $forceRecalculate))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/question-results-aggregation/bulk" & "?" & url_encoded_query_params, $(%bulkAggregateQuestionResultsRequest))
  constructResult[BulkAggregateQuestionResultsResponse1](response)


proc changeTicketState*(httpClient: HttpClient, tenantId: string, userId: string, id: string, changeTicketStateBody: ChangeTicketStateBody): (Option[ChangeTicketStateResponse1], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  query_params_list.add(("userId", $userId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/tickets/{id}/state" & "?" & url_encoded_query_params, $(%changeTicketStateBody))
  constructResult[ChangeTicketStateResponse1](response)


proc combineCommentsWithQuestionResults*(httpClient: HttpClient, tenantId: string, questionId: string, questionIds: seq[string], urlId: string, startDate: string, forceRecalculate: bool, minValue: float64, maxValue: float64, limit: float64): (Option[CombineCommentsWithQuestionResultsResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $questionId != "":
    query_params_list.add(("questionId", $questionId))
  if questionIds.len > 0:
    query_params_list.add(("questionIds", $questionIds.join(",")))
  if $urlId != "":
    query_params_list.add(("urlId", $urlId))
  if $startDate != "":
    query_params_list.add(("startDate", $startDate))
  if $forceRecalculate != "":
    query_params_list.add(("forceRecalculate", $forceRecalculate))
  if $minValue != "":
    query_params_list.add(("minValue", $minValue))
  if $maxValue != "":
    query_params_list.add(("maxValue", $maxValue))
  if $limit != "":
    query_params_list.add(("limit", $limit))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/question-results-aggregation/combine/comments" & "?" & url_encoded_query_params)
  constructResult[CombineCommentsWithQuestionResultsResponse](response)


proc createEmailTemplate*(httpClient: HttpClient, tenantId: string, createEmailTemplateBody: CreateEmailTemplateBody): (Option[CreateEmailTemplateResponse1], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/email-templates" & "?" & url_encoded_query_params, $(%createEmailTemplateBody))
  constructResult[CreateEmailTemplateResponse1](response)


proc createFeedPost*(httpClient: HttpClient, tenantId: string, createFeedPostParams: CreateFeedPostParams, broadcastId: string, isLive: bool, doSpamCheck: bool, skipDupCheck: bool): (Option[CreateFeedPostResponse1], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $broadcastId != "":
    query_params_list.add(("broadcastId", $broadcastId))
  if $isLive != "":
    query_params_list.add(("isLive", $isLive))
  if $doSpamCheck != "":
    query_params_list.add(("doSpamCheck", $doSpamCheck))
  if $skipDupCheck != "":
    query_params_list.add(("skipDupCheck", $skipDupCheck))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/feed-posts" & "?" & url_encoded_query_params, $(%createFeedPostParams))
  constructResult[CreateFeedPostResponse1](response)


proc createModerator*(httpClient: HttpClient, tenantId: string, createModeratorBody: CreateModeratorBody): (Option[CreateModeratorResponse1], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/moderators" & "?" & url_encoded_query_params, $(%createModeratorBody))
  constructResult[CreateModeratorResponse1](response)


proc createQuestionConfig*(httpClient: HttpClient, tenantId: string, createQuestionConfigBody: CreateQuestionConfigBody): (Option[CreateQuestionConfigResponse1], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/question-configs" & "?" & url_encoded_query_params, $(%createQuestionConfigBody))
  constructResult[CreateQuestionConfigResponse1](response)


proc createQuestionResult*(httpClient: HttpClient, tenantId: string, createQuestionResultBody: CreateQuestionResultBody): (Option[CreateQuestionResultResponse1], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/question-results" & "?" & url_encoded_query_params, $(%createQuestionResultBody))
  constructResult[CreateQuestionResultResponse1](response)


proc createSubscription*(httpClient: HttpClient, tenantId: string, createAPIUserSubscriptionData: CreateAPIUserSubscriptionData): (Option[CreateSubscriptionAPIResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/subscriptions" & "?" & url_encoded_query_params, $(%createAPIUserSubscriptionData))
  constructResult[CreateSubscriptionAPIResponse](response)


proc createTenant*(httpClient: HttpClient, tenantId: string, createTenantBody: CreateTenantBody): (Option[CreateTenantResponse1], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/tenants" & "?" & url_encoded_query_params, $(%createTenantBody))
  constructResult[CreateTenantResponse1](response)


proc createTenantPackage*(httpClient: HttpClient, tenantId: string, createTenantPackageBody: CreateTenantPackageBody): (Option[CreateTenantPackageResponse1], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/tenant-packages" & "?" & url_encoded_query_params, $(%createTenantPackageBody))
  constructResult[CreateTenantPackageResponse1](response)


proc createTenantUser*(httpClient: HttpClient, tenantId: string, createTenantUserBody: CreateTenantUserBody): (Option[CreateTenantUserResponse1], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/tenant-users" & "?" & url_encoded_query_params, $(%createTenantUserBody))
  constructResult[CreateTenantUserResponse1](response)


proc createTicket*(httpClient: HttpClient, tenantId: string, userId: string, createTicketBody: CreateTicketBody): (Option[CreateTicketResponse1], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  query_params_list.add(("userId", $userId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/tickets" & "?" & url_encoded_query_params, $(%createTicketBody))
  constructResult[CreateTicketResponse1](response)


proc createUserBadge*(httpClient: HttpClient, tenantId: string, createUserBadgeParams: CreateUserBadgeParams): (Option[CreateUserBadgeResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/user-badges" & "?" & url_encoded_query_params, $(%createUserBadgeParams))
  constructResult[CreateUserBadgeResponse](response)


proc createVote*(httpClient: HttpClient, tenantId: string, commentId: string, direction: string, userId: string, anonUserId: string): (Option[CreateVoteResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  query_params_list.add(("commentId", $commentId))
  query_params_list.add(("direction", $direction))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  if $anonUserId != "":
    query_params_list.add(("anonUserId", $anonUserId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/votes" & "?" & url_encoded_query_params)
  constructResult[CreateVoteResponse](response)


proc deleteComment*(httpClient: HttpClient, tenantId: string, id: string, contextUserId: string, isLive: bool): (Option[DeleteCommentResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $contextUserId != "":
    query_params_list.add(("contextUserId", $contextUserId))
  if $isLive != "":
    query_params_list.add(("isLive", $isLive))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/comments/{id}" & "?" & url_encoded_query_params)
  constructResult[DeleteCommentResponse](response)


proc deleteDomainConfig*(httpClient: HttpClient, tenantId: string, domain: string): (Option[DeleteDomainConfigResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/domain-configs/{domain}" & "?" & url_encoded_query_params)
  constructResult[DeleteDomainConfigResponse](response)


proc deleteEmailTemplate*(httpClient: HttpClient, tenantId: string, id: string): (Option[DeleteEmailTemplateResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/email-templates/{id}" & "?" & url_encoded_query_params)
  constructResult[DeleteEmailTemplateResponse](response)


proc deleteEmailTemplateRenderError*(httpClient: HttpClient, tenantId: string, id: string, errorId: string): (Option[DeleteEmailTemplateRenderErrorResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/email-templates/{id}/render-errors/{errorId}" & "?" & url_encoded_query_params)
  constructResult[DeleteEmailTemplateRenderErrorResponse](response)


proc deleteHashTag*(httpClient: HttpClient, tag: string, tenantId: string, deleteHashTagRequestBody: DeleteHashTagRequestBody): (Option[DeleteHashTagResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  if $tenantId != "":
    query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)
  let response = httpClient.request(basepath & fmt"/api/v1/hash-tags/{tag}" & "?" & url_encoded_query_params, httpMethod = HttpDelete, body = $(%deleteHashTagRequestBody))
  constructResult[DeleteHashTagResponse](response)


proc deleteModerator*(httpClient: HttpClient, tenantId: string, id: string, sendEmail: string): (Option[DeleteModeratorResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $sendEmail != "":
    query_params_list.add(("sendEmail", $sendEmail))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/moderators/{id}" & "?" & url_encoded_query_params)
  constructResult[DeleteModeratorResponse](response)


proc deleteNotificationCount*(httpClient: HttpClient, tenantId: string, id: string): (Option[DeleteNotificationCountResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/notification-count/{id}" & "?" & url_encoded_query_params)
  constructResult[DeleteNotificationCountResponse](response)


proc deletePage*(httpClient: HttpClient, tenantId: string, id: string): (Option[DeletePageAPIResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/pages/{id}" & "?" & url_encoded_query_params)
  constructResult[DeletePageAPIResponse](response)


proc deletePendingWebhookEvent*(httpClient: HttpClient, tenantId: string, id: string): (Option[DeletePendingWebhookEventResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/pending-webhook-events/{id}" & "?" & url_encoded_query_params)
  constructResult[DeletePendingWebhookEventResponse](response)


proc deleteQuestionConfig*(httpClient: HttpClient, tenantId: string, id: string): (Option[DeleteQuestionConfigResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/question-configs/{id}" & "?" & url_encoded_query_params)
  constructResult[DeleteQuestionConfigResponse](response)


proc deleteQuestionResult*(httpClient: HttpClient, tenantId: string, id: string): (Option[DeleteQuestionResultResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/question-results/{id}" & "?" & url_encoded_query_params)
  constructResult[DeleteQuestionResultResponse](response)


proc deleteSSOUser*(httpClient: HttpClient, tenantId: string, id: string, deleteComments: bool, commentDeleteMode: string): (Option[DeleteSSOUserAPIResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $deleteComments != "":
    query_params_list.add(("deleteComments", $deleteComments))
  if $commentDeleteMode != "":
    query_params_list.add(("commentDeleteMode", $commentDeleteMode))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/sso-users/{id}" & "?" & url_encoded_query_params)
  constructResult[DeleteSSOUserAPIResponse](response)


proc deleteSubscription*(httpClient: HttpClient, tenantId: string, id: string, userId: string): (Option[DeleteSubscriptionAPIResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/subscriptions/{id}" & "?" & url_encoded_query_params)
  constructResult[DeleteSubscriptionAPIResponse](response)


proc deleteTenant*(httpClient: HttpClient, tenantId: string, id: string, sure: string): (Option[DeleteTenantResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $sure != "":
    query_params_list.add(("sure", $sure))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/tenants/{id}" & "?" & url_encoded_query_params)
  constructResult[DeleteTenantResponse](response)


proc deleteTenantPackage*(httpClient: HttpClient, tenantId: string, id: string): (Option[DeleteTenantPackageResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/tenant-packages/{id}" & "?" & url_encoded_query_params)
  constructResult[DeleteTenantPackageResponse](response)


proc deleteTenantUser*(httpClient: HttpClient, tenantId: string, id: string, deleteComments: string, commentDeleteMode: string): (Option[DeleteTenantUserResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $deleteComments != "":
    query_params_list.add(("deleteComments", $deleteComments))
  if $commentDeleteMode != "":
    query_params_list.add(("commentDeleteMode", $commentDeleteMode))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/tenant-users/{id}" & "?" & url_encoded_query_params)
  constructResult[DeleteTenantUserResponse](response)


proc deleteUserBadge*(httpClient: HttpClient, tenantId: string, id: string): (Option[DeleteUserBadgeResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/user-badges/{id}" & "?" & url_encoded_query_params)
  constructResult[DeleteUserBadgeResponse](response)


proc deleteVote*(httpClient: HttpClient, tenantId: string, id: string, editKey: string): (Option[DeleteVoteResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $editKey != "":
    query_params_list.add(("editKey", $editKey))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.delete(basepath & fmt"/api/v1/votes/{id}" & "?" & url_encoded_query_params)
  constructResult[DeleteVoteResponse](response)


proc flagComment*(httpClient: HttpClient, tenantId: string, id: string, userId: string, anonUserId: string): (Option[FlagCommentResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  if $anonUserId != "":
    query_params_list.add(("anonUserId", $anonUserId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & fmt"/api/v1/comments/{id}/flag" & "?" & url_encoded_query_params)
  constructResult[FlagCommentResponse1](response)


proc getAuditLogs*(httpClient: HttpClient, tenantId: string, limit: float64, skip: float64, order: SORTDIR, after: float64, before: float64): (Option[GetAuditLogsResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $limit != "":
    query_params_list.add(("limit", $limit))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  if $order != "":
    query_params_list.add(("order", $order))
  if $after != "":
    query_params_list.add(("after", $after))
  if $before != "":
    query_params_list.add(("before", $before))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/audit-logs" & "?" & url_encoded_query_params)
  constructResult[GetAuditLogsResponse1](response)


proc getCachedNotificationCount*(httpClient: HttpClient, tenantId: string, id: string): (Option[GetCachedNotificationCountResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/notification-count/{id}" & "?" & url_encoded_query_params)
  constructResult[GetCachedNotificationCountResponse1](response)


proc getComment*(httpClient: HttpClient, tenantId: string, id: string): (Option[GetCommentResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/comments/{id}" & "?" & url_encoded_query_params)
  constructResult[GetCommentResponse](response)


proc getComments*(httpClient: HttpClient, tenantId: string, page: int, limit: int, skip: int, asTree: bool, skipChildren: int, limitChildren: int, maxTreeDepth: int, urlId: string, userId: string, anonUserId: string, contextUserId: string, hashTag: string, parentId: string, direction: SortDirections, fromDate: int64, toDate: int64): (Option[GetCommentsResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $page != "":
    query_params_list.add(("page", $page))
  if $limit != "":
    query_params_list.add(("limit", $limit))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  if $asTree != "":
    query_params_list.add(("asTree", $asTree))
  if $skipChildren != "":
    query_params_list.add(("skipChildren", $skipChildren))
  if $limitChildren != "":
    query_params_list.add(("limitChildren", $limitChildren))
  if $maxTreeDepth != "":
    query_params_list.add(("maxTreeDepth", $maxTreeDepth))
  if $urlId != "":
    query_params_list.add(("urlId", $urlId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  if $anonUserId != "":
    query_params_list.add(("anonUserId", $anonUserId))
  if $contextUserId != "":
    query_params_list.add(("contextUserId", $contextUserId))
  if $hashTag != "":
    query_params_list.add(("hashTag", $hashTag))
  if $parentId != "":
    query_params_list.add(("parentId", $parentId))
  if $direction != "":
    query_params_list.add(("direction", $direction))
  if $fromDate != "":
    query_params_list.add(("fromDate", $fromDate))
  if $toDate != "":
    query_params_list.add(("toDate", $toDate))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/comments" & "?" & url_encoded_query_params)
  constructResult[GetCommentsResponse](response)


proc getDomainConfig*(httpClient: HttpClient, tenantId: string, domain: string): (Option[GetDomainConfigResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/domain-configs/{domain}" & "?" & url_encoded_query_params)
  constructResult[GetDomainConfigResponse](response)


proc getDomainConfigs*(httpClient: HttpClient, tenantId: string): (Option[GetDomainConfigsResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/domain-configs" & "?" & url_encoded_query_params)
  constructResult[GetDomainConfigsResponse](response)


proc getEmailTemplate*(httpClient: HttpClient, tenantId: string, id: string): (Option[GetEmailTemplateResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/email-templates/{id}" & "?" & url_encoded_query_params)
  constructResult[GetEmailTemplateResponse1](response)


proc getEmailTemplateDefinitions*(httpClient: HttpClient, tenantId: string): (Option[GetEmailTemplateDefinitionsResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/email-templates/definitions" & "?" & url_encoded_query_params)
  constructResult[GetEmailTemplateDefinitionsResponse1](response)


proc getEmailTemplateRenderErrors*(httpClient: HttpClient, tenantId: string, id: string, skip: float64): (Option[GetEmailTemplateRenderErrorsResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/email-templates/{id}/render-errors" & "?" & url_encoded_query_params)
  constructResult[GetEmailTemplateRenderErrorsResponse1](response)


proc getEmailTemplates*(httpClient: HttpClient, tenantId: string, skip: float64): (Option[GetEmailTemplatesResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/email-templates" & "?" & url_encoded_query_params)
  constructResult[GetEmailTemplatesResponse1](response)


proc getFeedPosts*(httpClient: HttpClient, tenantId: string, afterId: string, limit: int, tags: seq[string]): (Option[GetFeedPostsResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $afterId != "":
    query_params_list.add(("afterId", $afterId))
  if $limit != "":
    query_params_list.add(("limit", $limit))
  if tags.len > 0:
    query_params_list.add(("tags", $tags.join(",")))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/feed-posts" & "?" & url_encoded_query_params)
  constructResult[GetFeedPostsResponse1](response)


proc getHashTags*(httpClient: HttpClient, tenantId: string, page: float64): (Option[GetHashTagsResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $page != "":
    query_params_list.add(("page", $page))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/hash-tags" & "?" & url_encoded_query_params)
  constructResult[GetHashTagsResponse1](response)


proc getModerator*(httpClient: HttpClient, tenantId: string, id: string): (Option[GetModeratorResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/moderators/{id}" & "?" & url_encoded_query_params)
  constructResult[GetModeratorResponse1](response)


proc getModerators*(httpClient: HttpClient, tenantId: string, skip: float64): (Option[GetModeratorsResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/moderators" & "?" & url_encoded_query_params)
  constructResult[GetModeratorsResponse1](response)


proc getNotificationCount*(httpClient: HttpClient, tenantId: string, userId: string, urlId: string, fromCommentId: string, viewed: bool, `type`: string): (Option[GetNotificationCountResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  if $urlId != "":
    query_params_list.add(("urlId", $urlId))
  if $fromCommentId != "":
    query_params_list.add(("fromCommentId", $fromCommentId))
  if $viewed != "":
    query_params_list.add(("viewed", $viewed))
  if $`type` != "":
    query_params_list.add(("type", $`type`))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/notifications/count" & "?" & url_encoded_query_params)
  constructResult[GetNotificationCountResponse1](response)


proc getNotifications*(httpClient: HttpClient, tenantId: string, userId: string, urlId: string, fromCommentId: string, viewed: bool, `type`: string, skip: float64): (Option[GetNotificationsResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  if $urlId != "":
    query_params_list.add(("urlId", $urlId))
  if $fromCommentId != "":
    query_params_list.add(("fromCommentId", $fromCommentId))
  if $viewed != "":
    query_params_list.add(("viewed", $viewed))
  if $`type` != "":
    query_params_list.add(("type", $`type`))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/notifications" & "?" & url_encoded_query_params)
  constructResult[GetNotificationsResponse1](response)


proc getPageByURLId*(httpClient: HttpClient, tenantId: string, urlId: string): (Option[GetPageByURLIdAPIResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  query_params_list.add(("urlId", $urlId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/pages/by-url-id" & "?" & url_encoded_query_params)
  constructResult[GetPageByURLIdAPIResponse](response)


proc getPages*(httpClient: HttpClient, tenantId: string): (Option[GetPagesAPIResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/pages" & "?" & url_encoded_query_params)
  constructResult[GetPagesAPIResponse](response)


proc getPendingWebhookEventCount*(httpClient: HttpClient, tenantId: string, commentId: string, externalId: string, eventType: string, `type`: string, domain: string, attemptCountGT: float64): (Option[GetPendingWebhookEventCountResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $commentId != "":
    query_params_list.add(("commentId", $commentId))
  if $externalId != "":
    query_params_list.add(("externalId", $externalId))
  if $eventType != "":
    query_params_list.add(("eventType", $eventType))
  if $`type` != "":
    query_params_list.add(("type", $`type`))
  if $domain != "":
    query_params_list.add(("domain", $domain))
  if $attemptCountGT != "":
    query_params_list.add(("attemptCountGT", $attemptCountGT))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/pending-webhook-events/count" & "?" & url_encoded_query_params)
  constructResult[GetPendingWebhookEventCountResponse1](response)


proc getPendingWebhookEvents*(httpClient: HttpClient, tenantId: string, commentId: string, externalId: string, eventType: string, `type`: string, domain: string, attemptCountGT: float64, skip: float64): (Option[GetPendingWebhookEventsResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $commentId != "":
    query_params_list.add(("commentId", $commentId))
  if $externalId != "":
    query_params_list.add(("externalId", $externalId))
  if $eventType != "":
    query_params_list.add(("eventType", $eventType))
  if $`type` != "":
    query_params_list.add(("type", $`type`))
  if $domain != "":
    query_params_list.add(("domain", $domain))
  if $attemptCountGT != "":
    query_params_list.add(("attemptCountGT", $attemptCountGT))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/pending-webhook-events" & "?" & url_encoded_query_params)
  constructResult[GetPendingWebhookEventsResponse1](response)


proc getQuestionConfig*(httpClient: HttpClient, tenantId: string, id: string): (Option[GetQuestionConfigResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/question-configs/{id}" & "?" & url_encoded_query_params)
  constructResult[GetQuestionConfigResponse1](response)


proc getQuestionConfigs*(httpClient: HttpClient, tenantId: string, skip: float64): (Option[GetQuestionConfigsResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/question-configs" & "?" & url_encoded_query_params)
  constructResult[GetQuestionConfigsResponse1](response)


proc getQuestionResult*(httpClient: HttpClient, tenantId: string, id: string): (Option[GetQuestionResultResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/question-results/{id}" & "?" & url_encoded_query_params)
  constructResult[GetQuestionResultResponse1](response)


proc getQuestionResults*(httpClient: HttpClient, tenantId: string, urlId: string, userId: string, startDate: string, questionId: string, questionIds: string, skip: float64): (Option[GetQuestionResultsResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $urlId != "":
    query_params_list.add(("urlId", $urlId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  if $startDate != "":
    query_params_list.add(("startDate", $startDate))
  if $questionId != "":
    query_params_list.add(("questionId", $questionId))
  if $questionIds != "":
    query_params_list.add(("questionIds", $questionIds))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/question-results" & "?" & url_encoded_query_params)
  constructResult[GetQuestionResultsResponse1](response)


proc getSSOUserByEmail*(httpClient: HttpClient, tenantId: string, email: string): (Option[GetSSOUserByEmailAPIResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/sso-users/by-email/{email}" & "?" & url_encoded_query_params)
  constructResult[GetSSOUserByEmailAPIResponse](response)


proc getSSOUserById*(httpClient: HttpClient, tenantId: string, id: string): (Option[GetSSOUserByIdAPIResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/sso-users/by-id/{id}" & "?" & url_encoded_query_params)
  constructResult[GetSSOUserByIdAPIResponse](response)


proc getSSOUsers*(httpClient: HttpClient, tenantId: string, skip: int): (Option[GetSSOUsersResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/sso-users" & "?" & url_encoded_query_params)
  constructResult[GetSSOUsersResponse](response)


proc getSubscriptions*(httpClient: HttpClient, tenantId: string, userId: string): (Option[GetSubscriptionsAPIResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/subscriptions" & "?" & url_encoded_query_params)
  constructResult[GetSubscriptionsAPIResponse](response)


proc getTenant*(httpClient: HttpClient, tenantId: string, id: string): (Option[GetTenantResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/tenants/{id}" & "?" & url_encoded_query_params)
  constructResult[GetTenantResponse1](response)


proc getTenantDailyUsages*(httpClient: HttpClient, tenantId: string, yearNumber: float64, monthNumber: float64, dayNumber: float64, skip: float64): (Option[GetTenantDailyUsagesResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $yearNumber != "":
    query_params_list.add(("yearNumber", $yearNumber))
  if $monthNumber != "":
    query_params_list.add(("monthNumber", $monthNumber))
  if $dayNumber != "":
    query_params_list.add(("dayNumber", $dayNumber))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/tenant-daily-usage" & "?" & url_encoded_query_params)
  constructResult[GetTenantDailyUsagesResponse1](response)


proc getTenantPackage*(httpClient: HttpClient, tenantId: string, id: string): (Option[GetTenantPackageResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/tenant-packages/{id}" & "?" & url_encoded_query_params)
  constructResult[GetTenantPackageResponse1](response)


proc getTenantPackages*(httpClient: HttpClient, tenantId: string, skip: float64): (Option[GetTenantPackagesResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/tenant-packages" & "?" & url_encoded_query_params)
  constructResult[GetTenantPackagesResponse1](response)


proc getTenantUser*(httpClient: HttpClient, tenantId: string, id: string): (Option[GetTenantUserResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/tenant-users/{id}" & "?" & url_encoded_query_params)
  constructResult[GetTenantUserResponse1](response)


proc getTenantUsers*(httpClient: HttpClient, tenantId: string, skip: float64): (Option[GetTenantUsersResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/tenant-users" & "?" & url_encoded_query_params)
  constructResult[GetTenantUsersResponse1](response)


proc getTenants*(httpClient: HttpClient, tenantId: string, meta: string, skip: float64): (Option[GetTenantsResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $meta != "":
    query_params_list.add(("meta", $meta))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/tenants" & "?" & url_encoded_query_params)
  constructResult[GetTenantsResponse1](response)


proc getTicket*(httpClient: HttpClient, tenantId: string, id: string, userId: string): (Option[GetTicketResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/tickets/{id}" & "?" & url_encoded_query_params)
  constructResult[GetTicketResponse1](response)


proc getTickets*(httpClient: HttpClient, tenantId: string, userId: string, state: float64, skip: float64, limit: float64): (Option[GetTicketsResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  if $state != "":
    query_params_list.add(("state", $state))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  if $limit != "":
    query_params_list.add(("limit", $limit))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/tickets" & "?" & url_encoded_query_params)
  constructResult[GetTicketsResponse1](response)


proc getUser*(httpClient: HttpClient, tenantId: string, id: string): (Option[GetUserResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/users/{id}" & "?" & url_encoded_query_params)
  constructResult[GetUserResponse1](response)


proc getUserBadge*(httpClient: HttpClient, tenantId: string, id: string): (Option[GetUserBadgeResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/user-badges/{id}" & "?" & url_encoded_query_params)
  constructResult[GetUserBadgeResponse](response)


proc getUserBadgeProgressById*(httpClient: HttpClient, tenantId: string, id: string): (Option[GetUserBadgeProgressByIdResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/user-badge-progress/{id}" & "?" & url_encoded_query_params)
  constructResult[GetUserBadgeProgressByIdResponse](response)


proc getUserBadgeProgressByUserId*(httpClient: HttpClient, tenantId: string, userId: string): (Option[GetUserBadgeProgressByUserIdResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & fmt"/api/v1/user-badge-progress/user/{userId}" & "?" & url_encoded_query_params)
  constructResult[GetUserBadgeProgressByUserIdResponse](response)


proc getUserBadgeProgressList*(httpClient: HttpClient, tenantId: string, userId: string, limit: float64, skip: float64): (Option[GetUserBadgeProgressListResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  if $limit != "":
    query_params_list.add(("limit", $limit))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/user-badge-progress" & "?" & url_encoded_query_params)
  constructResult[GetUserBadgeProgressListResponse](response)


proc getUserBadges*(httpClient: HttpClient, tenantId: string, userId: string, badgeId: string, `type`: float64, displayedOnComments: bool, limit: float64, skip: float64): (Option[GetUserBadgesResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  if $badgeId != "":
    query_params_list.add(("badgeId", $badgeId))
  if $`type` != "":
    query_params_list.add(("type", $`type`))
  if $displayedOnComments != "":
    query_params_list.add(("displayedOnComments", $displayedOnComments))
  if $limit != "":
    query_params_list.add(("limit", $limit))
  if $skip != "":
    query_params_list.add(("skip", $skip))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/user-badges" & "?" & url_encoded_query_params)
  constructResult[GetUserBadgesResponse](response)


proc getVotes*(httpClient: HttpClient, tenantId: string, urlId: string): (Option[GetVotesResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  query_params_list.add(("urlId", $urlId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/votes" & "?" & url_encoded_query_params)
  constructResult[GetVotesResponse1](response)


proc getVotesForUser*(httpClient: HttpClient, tenantId: string, urlId: string, userId: string, anonUserId: string): (Option[GetVotesForUserResponse1], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  query_params_list.add(("urlId", $urlId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  if $anonUserId != "":
    query_params_list.add(("anonUserId", $anonUserId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.get(basepath & "/api/v1/votes/for-user" & "?" & url_encoded_query_params)
  constructResult[GetVotesForUserResponse1](response)


proc patchDomainConfig*(httpClient: HttpClient, tenantId: string, domainToUpdate: string, patchDomainConfigParams: PatchDomainConfigParams): (Option[PatchDomainConfigResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/domain-configs/{domainToUpdate}" & "?" & url_encoded_query_params, $(%patchDomainConfigParams))
  constructResult[PatchDomainConfigResponse](response)


proc patchHashTag*(httpClient: HttpClient, tag: string, tenantId: string, updateHashTagBody: UpdateHashTagBody): (Option[PatchHashTagResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  if $tenantId != "":
    query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/hash-tags/{tag}" & "?" & url_encoded_query_params, $(%updateHashTagBody))
  constructResult[PatchHashTagResponse](response)


proc patchPage*(httpClient: HttpClient, tenantId: string, id: string, updateAPIPageData: UpdateAPIPageData): (Option[PatchPageAPIResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/pages/{id}" & "?" & url_encoded_query_params, $(%updateAPIPageData))
  constructResult[PatchPageAPIResponse](response)


proc patchSSOUser*(httpClient: HttpClient, tenantId: string, id: string, updateAPISSOUserData: UpdateAPISSOUserData, updateComments: bool): (Option[PatchSSOUserAPIResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $updateComments != "":
    query_params_list.add(("updateComments", $updateComments))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/sso-users/{id}" & "?" & url_encoded_query_params, $(%updateAPISSOUserData))
  constructResult[PatchSSOUserAPIResponse](response)


proc putDomainConfig*(httpClient: HttpClient, tenantId: string, domainToUpdate: string, updateDomainConfigParams: UpdateDomainConfigParams): (Option[PutDomainConfigResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.put(basepath & fmt"/api/v1/domain-configs/{domainToUpdate}" & "?" & url_encoded_query_params, $(%updateDomainConfigParams))
  constructResult[PutDomainConfigResponse](response)


proc putSSOUser*(httpClient: HttpClient, tenantId: string, id: string, updateAPISSOUserData: UpdateAPISSOUserData, updateComments: bool): (Option[PutSSOUserAPIResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $updateComments != "":
    query_params_list.add(("updateComments", $updateComments))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.put(basepath & fmt"/api/v1/sso-users/{id}" & "?" & url_encoded_query_params, $(%updateAPISSOUserData))
  constructResult[PutSSOUserAPIResponse](response)


proc renderEmailTemplate*(httpClient: HttpClient, tenantId: string, renderEmailTemplateBody: RenderEmailTemplateBody, locale: string): (Option[RenderEmailTemplateResponse1], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $locale != "":
    query_params_list.add(("locale", $locale))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/email-templates/render" & "?" & url_encoded_query_params, $(%renderEmailTemplateBody))
  constructResult[RenderEmailTemplateResponse1](response)


proc replaceTenantPackage*(httpClient: HttpClient, tenantId: string, id: string, replaceTenantPackageBody: ReplaceTenantPackageBody): (Option[ReplaceTenantPackageResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.put(basepath & fmt"/api/v1/tenant-packages/{id}" & "?" & url_encoded_query_params, $(%replaceTenantPackageBody))
  constructResult[ReplaceTenantPackageResponse](response)


proc replaceTenantUser*(httpClient: HttpClient, tenantId: string, id: string, replaceTenantUserBody: ReplaceTenantUserBody, updateComments: string): (Option[ReplaceTenantUserResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $updateComments != "":
    query_params_list.add(("updateComments", $updateComments))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.put(basepath & fmt"/api/v1/tenant-users/{id}" & "?" & url_encoded_query_params, $(%replaceTenantUserBody))
  constructResult[ReplaceTenantUserResponse](response)


proc saveComment*(httpClient: HttpClient, tenantId: string, createCommentParams: CreateCommentParams, isLive: bool, doSpamCheck: bool, sendEmails: bool, populateNotifications: bool): (Option[SaveCommentResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $isLive != "":
    query_params_list.add(("isLive", $isLive))
  if $doSpamCheck != "":
    query_params_list.add(("doSpamCheck", $doSpamCheck))
  if $sendEmails != "":
    query_params_list.add(("sendEmails", $sendEmails))
  if $populateNotifications != "":
    query_params_list.add(("populateNotifications", $populateNotifications))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/comments" & "?" & url_encoded_query_params, $(%createCommentParams))
  constructResult[SaveCommentResponse](response)


proc saveCommentsBulk*(httpClient: HttpClient, tenantId: string, createCommentParams: seq[CreateCommentParams], isLive: bool, doSpamCheck: bool, sendEmails: bool, populateNotifications: bool): (Option[seq[SaveCommentsBulkResponse]], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $isLive != "":
    query_params_list.add(("isLive", $isLive))
  if $doSpamCheck != "":
    query_params_list.add(("doSpamCheck", $doSpamCheck))
  if $sendEmails != "":
    query_params_list.add(("sendEmails", $sendEmails))
  if $populateNotifications != "":
    query_params_list.add(("populateNotifications", $populateNotifications))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & "/api/v1/comments/bulk" & "?" & url_encoded_query_params, $(%createCommentParams))
  constructResult[seq[SaveCommentsBulkResponse]](response)


proc sendInvite*(httpClient: HttpClient, tenantId: string, id: string, fromName: string): (Option[SendInviteResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  query_params_list.add(("fromName", $fromName))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & fmt"/api/v1/moderators/{id}/send-invite" & "?" & url_encoded_query_params)
  constructResult[SendInviteResponse](response)


proc sendLoginLink*(httpClient: HttpClient, tenantId: string, id: string, redirectURL: string): (Option[SendLoginLinkResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $redirectURL != "":
    query_params_list.add(("redirectURL", $redirectURL))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & fmt"/api/v1/tenant-users/{id}/send-login-link" & "?" & url_encoded_query_params)
  constructResult[SendLoginLinkResponse](response)


proc unBlockUserFromComment*(httpClient: HttpClient, tenantId: string, id: string, unBlockFromCommentParams: UnBlockFromCommentParams, userId: string, anonUserId: string): (Option[UnBlockUserFromCommentResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  if $anonUserId != "":
    query_params_list.add(("anonUserId", $anonUserId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & fmt"/api/v1/comments/{id}/un-block" & "?" & url_encoded_query_params, $(%unBlockFromCommentParams))
  constructResult[UnBlockUserFromCommentResponse](response)


proc unFlagComment*(httpClient: HttpClient, tenantId: string, id: string, userId: string, anonUserId: string): (Option[UnFlagCommentResponse], Response) =
  ## 
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  if $anonUserId != "":
    query_params_list.add(("anonUserId", $anonUserId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.post(basepath & fmt"/api/v1/comments/{id}/un-flag" & "?" & url_encoded_query_params)
  constructResult[UnFlagCommentResponse](response)


proc updateComment*(httpClient: HttpClient, tenantId: string, id: string, updatableCommentParams: UpdatableCommentParams, contextUserId: string, doSpamCheck: bool, isLive: bool): (Option[UpdateCommentResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $contextUserId != "":
    query_params_list.add(("contextUserId", $contextUserId))
  if $doSpamCheck != "":
    query_params_list.add(("doSpamCheck", $doSpamCheck))
  if $isLive != "":
    query_params_list.add(("isLive", $isLive))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/comments/{id}" & "?" & url_encoded_query_params, $(%updatableCommentParams))
  constructResult[UpdateCommentResponse](response)


proc updateEmailTemplate*(httpClient: HttpClient, tenantId: string, id: string, updateEmailTemplateBody: UpdateEmailTemplateBody): (Option[UpdateEmailTemplateResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/email-templates/{id}" & "?" & url_encoded_query_params, $(%updateEmailTemplateBody))
  constructResult[UpdateEmailTemplateResponse](response)


proc updateFeedPost*(httpClient: HttpClient, tenantId: string, id: string, feedPost: FeedPost): (Option[UpdateFeedPostResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/feed-posts/{id}" & "?" & url_encoded_query_params, $(%feedPost))
  constructResult[UpdateFeedPostResponse](response)


proc updateModerator*(httpClient: HttpClient, tenantId: string, id: string, updateModeratorBody: UpdateModeratorBody): (Option[UpdateModeratorResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/moderators/{id}" & "?" & url_encoded_query_params, $(%updateModeratorBody))
  constructResult[UpdateModeratorResponse](response)


proc updateNotification*(httpClient: HttpClient, tenantId: string, id: string, updateNotificationBody: UpdateNotificationBody, userId: string): (Option[UpdateNotificationResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/notifications/{id}" & "?" & url_encoded_query_params, $(%updateNotificationBody))
  constructResult[UpdateNotificationResponse](response)


proc updateQuestionConfig*(httpClient: HttpClient, tenantId: string, id: string, updateQuestionConfigBody: UpdateQuestionConfigBody): (Option[UpdateQuestionConfigResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/question-configs/{id}" & "?" & url_encoded_query_params, $(%updateQuestionConfigBody))
  constructResult[UpdateQuestionConfigResponse](response)


proc updateQuestionResult*(httpClient: HttpClient, tenantId: string, id: string, updateQuestionResultBody: UpdateQuestionResultBody): (Option[UpdateQuestionResultResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/question-results/{id}" & "?" & url_encoded_query_params, $(%updateQuestionResultBody))
  constructResult[UpdateQuestionResultResponse](response)


proc updateSubscription*(httpClient: HttpClient, tenantId: string, id: string, updateAPIUserSubscriptionData: UpdateAPIUserSubscriptionData, userId: string): (Option[UpdateSubscriptionAPIResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $userId != "":
    query_params_list.add(("userId", $userId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/subscriptions/{id}" & "?" & url_encoded_query_params, $(%updateAPIUserSubscriptionData))
  constructResult[UpdateSubscriptionAPIResponse](response)


proc updateTenant*(httpClient: HttpClient, tenantId: string, id: string, updateTenantBody: UpdateTenantBody): (Option[UpdateTenantResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/tenants/{id}" & "?" & url_encoded_query_params, $(%updateTenantBody))
  constructResult[UpdateTenantResponse](response)


proc updateTenantPackage*(httpClient: HttpClient, tenantId: string, id: string, updateTenantPackageBody: UpdateTenantPackageBody): (Option[UpdateTenantPackageResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/tenant-packages/{id}" & "?" & url_encoded_query_params, $(%updateTenantPackageBody))
  constructResult[UpdateTenantPackageResponse](response)


proc updateTenantUser*(httpClient: HttpClient, tenantId: string, id: string, updateTenantUserBody: UpdateTenantUserBody, updateComments: string): (Option[UpdateTenantUserResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  if $updateComments != "":
    query_params_list.add(("updateComments", $updateComments))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.patch(basepath & fmt"/api/v1/tenant-users/{id}" & "?" & url_encoded_query_params, $(%updateTenantUserBody))
  constructResult[UpdateTenantUserResponse](response)


proc updateUserBadge*(httpClient: HttpClient, tenantId: string, id: string, updateUserBadgeParams: UpdateUserBadgeParams): (Option[UpdateUserBadgeResponse], Response) =
  ## 
  httpClient.headers["Content-Type"] = "application/json"
  var query_params_list: seq[(string, string)] = @[]
  query_params_list.add(("tenantId", $tenantId))
  let url_encoded_query_params = encodeQuery(query_params_list)

  let response = httpClient.put(basepath & fmt"/api/v1/user-badges/{id}" & "?" & url_encoded_query_params, $(%updateUserBadgeParams))
  constructResult[UpdateUserBadgeResponse](response)

