#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type APIBannedUser* = object
  ## 
  id*: string
  tenantId*: string
  userId*: Option[string]
  email*: Option[string]
  username*: Option[string]
  ipHash*: Option[string]
  createdAt*: string
  bannedByUserId*: string
  bannedCommentText*: string
  banType*: string
  bannedUntil*: Option[string]
  hasEmailWildcard*: bool
  banReason*: Option[string]


# Custom JSON deserialization for APIBannedUser with custom field names
proc to*(node: JsonNode, T: typedesc[APIBannedUser]): APIBannedUser =
  result = APIBannedUser()
  if node.kind == JObject:
    if node.hasKey("_id"):
      result.id = to(node["_id"], string)
    if node.hasKey("tenantId"):
      result.tenantId = to(node["tenantId"], string)
    if node.hasKey("userId") and node["userId"].kind != JNull:
      result.userId = some(to(node["userId"], typeof(result.userId.get())))
    if node.hasKey("email") and node["email"].kind != JNull:
      result.email = some(to(node["email"], typeof(result.email.get())))
    if node.hasKey("username") and node["username"].kind != JNull:
      result.username = some(to(node["username"], typeof(result.username.get())))
    if node.hasKey("ipHash") and node["ipHash"].kind != JNull:
      result.ipHash = some(to(node["ipHash"], typeof(result.ipHash.get())))
    if node.hasKey("createdAt"):
      result.createdAt = to(node["createdAt"], string)
    if node.hasKey("bannedByUserId"):
      result.bannedByUserId = to(node["bannedByUserId"], string)
    if node.hasKey("bannedCommentText"):
      result.bannedCommentText = to(node["bannedCommentText"], string)
    if node.hasKey("banType"):
      result.banType = to(node["banType"], string)
    if node.hasKey("bannedUntil") and node["bannedUntil"].kind != JNull:
      result.bannedUntil = some(to(node["bannedUntil"], typeof(result.bannedUntil.get())))
    if node.hasKey("hasEmailWildcard"):
      result.hasEmailWildcard = to(node["hasEmailWildcard"], bool)
    if node.hasKey("banReason") and node["banReason"].kind != JNull:
      result.banReason = some(to(node["banReason"], typeof(result.banReason.get())))

# Custom JSON serialization for APIBannedUser with custom field names
proc `%`*(obj: APIBannedUser): JsonNode =
  result = newJObject()
  result["_id"] = %obj.id
  result["tenantId"] = %obj.tenantId
  if obj.userId.isSome():
    result["userId"] = %obj.userId.get()
  if obj.email.isSome():
    result["email"] = %obj.email.get()
  if obj.username.isSome():
    result["username"] = %obj.username.get()
  if obj.ipHash.isSome():
    result["ipHash"] = %obj.ipHash.get()
  result["createdAt"] = %obj.createdAt
  result["bannedByUserId"] = %obj.bannedByUserId
  result["bannedCommentText"] = %obj.bannedCommentText
  result["banType"] = %obj.banType
  if obj.bannedUntil.isSome():
    result["bannedUntil"] = %obj.bannedUntil.get()
  result["hasEmailWildcard"] = %obj.hasEmailWildcard
  if obj.banReason.isSome():
    result["banReason"] = %obj.banReason.get()

