#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_aggregate_time_bucket

type BulkAggregateQuestionItem* = object
  ## 
  aggId*: string
  questionId*: string
  questionIds*: seq[string]
  urlId*: string
  timeBucket*: AggregateTimeBucket
  startDate*: string

