#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status

type ReactFeedPostResponse* = object
  ## 
  status*: APIStatus
  reactType*: string
  isUndo*: bool


# Custom JSON deserialization for ReactFeedPostResponse with custom field names
proc to*(node: JsonNode, T: typedesc[ReactFeedPostResponse]): ReactFeedPostResponse =
  result = ReactFeedPostResponse()
  if node.kind == JObject:
    if node.hasKey("status"):
      result.status = model_api_status.to(node["status"], APIStatus)
    if node.hasKey("reactType"):
      result.reactType = to(node["reactType"], string)
    if node.hasKey("isUndo"):
      result.isUndo = to(node["isUndo"], bool)

# Custom JSON serialization for ReactFeedPostResponse with custom field names
proc `%`*(obj: ReactFeedPostResponse): JsonNode =
  result = newJObject()
  result["status"] = %obj.status
  result["reactType"] = %obj.reactType
  result["isUndo"] = %obj.isUndo
