#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_vote_response
import model_vote_response_user

# AnyOf type
type PostVoteResponseKind* {.pure.} = enum
  VoteResponseVariant
  APIErrorVariant

type PostVoteResponse* = object
  ## 
  case kind*: PostVoteResponseKind
  of PostVoteResponseKind.VoteResponseVariant:
    VoteResponseValue*: VoteResponse
  of PostVoteResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[PostVoteResponse]): PostVoteResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return PostVoteResponse(kind: PostVoteResponseKind.VoteResponseVariant, VoteResponseValue: to(node, VoteResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as VoteResponse: ", e.msg
  try:
    return PostVoteResponse(kind: PostVoteResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of PostVoteResponse. JSON: " & $node)

