#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables


type ImageContentProfanityLevel* {.pure.} = enum
  Off
  Low
  Medium
  High

func `%`*(v: ImageContentProfanityLevel): JsonNode =
  result = case v:
    of ImageContentProfanityLevel.Off: %"off"
    of ImageContentProfanityLevel.Low: %"low"
    of ImageContentProfanityLevel.Medium: %"medium"
    of ImageContentProfanityLevel.High: %"high"

func `$`*(v: ImageContentProfanityLevel): string =
  result = case v:
    of ImageContentProfanityLevel.Off: $("off")
    of ImageContentProfanityLevel.Low: $("low")
    of ImageContentProfanityLevel.Medium: $("medium")
    of ImageContentProfanityLevel.High: $("high")

