#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_user

type GetUserResponse* = object
  ## 
  status*: APIStatus
  user*: User


# Custom JSON deserialization for GetUserResponse with custom field names
proc to*(node: JsonNode, T: typedesc[GetUserResponse]): GetUserResponse =
  result = GetUserResponse()
  if node.kind == JObject:
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)
    if node.hasKey("user"):
      result.user = to(node["user"], User)

# Custom JSON serialization for GetUserResponse with custom field names
proc `%`*(obj: GetUserResponse): JsonNode =
  result = newJObject()
  result["status"] = %obj.status
  result["user"] = %obj.user

