#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type SSOSecurityLevel* {.pure.} = enum
  `0`
  `1`

func `%`*(v: SSOSecurityLevel): JsonNode =
  result = case v:
    of SSOSecurityLevel.`0`: %0
    of SSOSecurityLevel.`1`: %1

func `$`*(v: SSOSecurityLevel): string =
  result = case v:
    of SSOSecurityLevel.`0`: $(0)
    of SSOSecurityLevel.`1`: $(1)

proc to*(node: JsonNode, T: typedesc[SSOSecurityLevel]): SSOSecurityLevel =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum SSOSecurityLevel, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $(0):
    return SSOSecurityLevel.`0`
  of $(1):
    return SSOSecurityLevel.`1`
  else:
    raise newException(ValueError, "Invalid enum value for SSOSecurityLevel: " & strVal)

