#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_get_tenant_manual_badges_response
import model_tenant_badge

# AnyOf type
type GetManualBadgesResponseKind* {.pure.} = enum
  GetTenantManualBadgesResponseVariant
  APIErrorVariant

type GetManualBadgesResponse* = object
  ## 
  case kind*: GetManualBadgesResponseKind
  of GetManualBadgesResponseKind.GetTenantManualBadgesResponseVariant:
    GetTenantManualBadgesResponseValue*: GetTenantManualBadgesResponse
  of GetManualBadgesResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetManualBadgesResponse]): GetManualBadgesResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetManualBadgesResponse(kind: GetManualBadgesResponseKind.GetTenantManualBadgesResponseVariant, GetTenantManualBadgesResponseValue: to(node, GetTenantManualBadgesResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetTenantManualBadgesResponse: ", e.msg
  try:
    return GetManualBadgesResponse(kind: GetManualBadgesResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetManualBadgesResponse. JSON: " & $node)

