#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_moderation_page_search_projected
import model_moderation_user_search_projected

type ModerationSuggestResponse* = object
  ## 
  status*: string
  pages*: Option[seq[ModerationPageSearchProjected]]
  users*: Option[seq[ModerationUserSearchProjected]]
  code*: Option[string]


# Custom JSON deserialization for ModerationSuggestResponse with custom field names
proc to*(node: JsonNode, T: typedesc[ModerationSuggestResponse]): ModerationSuggestResponse =
  result = ModerationSuggestResponse()
  if node.kind == JObject:
    if node.hasKey("status"):
      result.status = to(node["status"], string)
    if node.hasKey("pages") and node["pages"].kind != JNull:
      result.pages = some(to(node["pages"], typeof(result.pages.get())))
    if node.hasKey("users") and node["users"].kind != JNull:
      # Optional array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["users"]
      if arrayNode.kind == JArray:
        var arr: seq[ModerationUserSearchProjected] = @[]
        for item in arrayNode.items:
          arr.add(to(item, ModerationUserSearchProjected))
        result.users = some(arr)
    if node.hasKey("code") and node["code"].kind != JNull:
      result.code = some(to(node["code"], typeof(result.code.get())))

# Custom JSON serialization for ModerationSuggestResponse with custom field names
proc `%`*(obj: ModerationSuggestResponse): JsonNode =
  result = newJObject()
  result["status"] = %obj.status
  if obj.pages.isSome():
    result["pages"] = %obj.pages.get()
  if obj.users.isSome():
    result["users"] = %obj.users.get()
  if obj.code.isSome():
    result["code"] = %obj.code.get()

