#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_api_ticket
import model_custom_config_parameters
import model_get_tickets_response

# AnyOf type
type GetTickets200responseKind* {.pure.} = enum
  GetTicketsResponseVariant
  APIErrorVariant

type GetTickets200response* = object
  ## 
  case kind*: GetTickets200responseKind
  of GetTickets200responseKind.GetTicketsResponseVariant:
    GetTicketsResponseValue*: GetTicketsResponse
  of GetTickets200responseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetTickets200response]): GetTickets200response =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetTickets200response(kind: GetTickets200responseKind.GetTicketsResponseVariant, GetTicketsResponseValue: to(node, GetTicketsResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetTicketsResponse: ", e.msg
  try:
    return GetTickets200response(kind: GetTickets200responseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetTickets200response. JSON: " & $node)

