#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_get_votes_response
import model_public_vote

# AnyOf type
type GetVotes200responseKind* {.pure.} = enum
  GetVotesResponseVariant
  APIErrorVariant

type GetVotes200response* = object
  ## 
  case kind*: GetVotes200responseKind
  of GetVotes200responseKind.GetVotesResponseVariant:
    GetVotesResponseValue*: GetVotesResponse
  of GetVotes200responseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetVotes200response]): GetVotes200response =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetVotes200response(kind: GetVotes200responseKind.GetVotesResponseVariant, GetVotesResponseValue: to(node, GetVotesResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetVotesResponse: ", e.msg
  try:
    return GetVotes200response(kind: GetVotes200responseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetVotes200response. JSON: " & $node)

