#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_moderation_api_comment

type ModerationAPICommentResponse* = object
  ## 
  comment*: ModerationAPIComment
  status*: APIStatus


# Custom JSON deserialization for ModerationAPICommentResponse with custom field names
proc to*(node: JsonNode, T: typedesc[ModerationAPICommentResponse]): ModerationAPICommentResponse =
  result = ModerationAPICommentResponse()
  if node.kind == JObject:
    if node.hasKey("comment"):
      result.comment = to(node["comment"], ModerationAPIComment)
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)

# Custom JSON serialization for ModerationAPICommentResponse with custom field names
proc `%`*(obj: ModerationAPICommentResponse): JsonNode =
  result = newJObject()
  result["comment"] = %obj.comment
  result["status"] = %obj.status

