#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_get_question_config_response
import model_question_config

# AnyOf type
type GetQuestionConfigResponse1Kind* {.pure.} = enum
  GetQuestionConfigResponseVariant
  APIErrorVariant

type GetQuestionConfigResponse1* = object
  ## 
  case kind*: GetQuestionConfigResponse1Kind
  of GetQuestionConfigResponse1Kind.GetQuestionConfigResponseVariant:
    GetQuestionConfigResponseValue*: GetQuestionConfigResponse
  of GetQuestionConfigResponse1Kind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetQuestionConfigResponse1]): GetQuestionConfigResponse1 =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetQuestionConfigResponse1(kind: GetQuestionConfigResponse1Kind.GetQuestionConfigResponseVariant, GetQuestionConfigResponseValue: to(node, GetQuestionConfigResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetQuestionConfigResponse: ", e.msg
  try:
    return GetQuestionConfigResponse1(kind: GetQuestionConfigResponse1Kind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetQuestionConfigResponse1. JSON: " & $node)

