#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type TenantBadge* = object
  ## 
  id*: string
  tenantId*: string
  createdByUserId*: string
  createdAt*: string
  enabled*: bool
  urlId*: Option[string]
  `type`*: float64
  threshold*: float64
  uses*: float64
  name*: string
  description*: string
  displayLabel*: string
  displaySrc*: Option[string]
  backgroundColor*: Option[string]
  borderColor*: Option[string]
  textColor*: Option[string]
  cssClass*: Option[string]
  veteranUserThresholdMillis*: Option[float64]
  isAwaitingReprocess*: bool
  isAwaitingDeletion*: bool
  replacesBadgeId*: Option[string]


# Custom JSON deserialization for TenantBadge with custom field names
proc to*(node: JsonNode, T: typedesc[TenantBadge]): TenantBadge =
  result = TenantBadge()
  if node.kind == JObject:
    if node.hasKey("_id"):
      result.id = to(node["_id"], string)
    if node.hasKey("tenantId"):
      result.tenantId = to(node["tenantId"], string)
    if node.hasKey("createdByUserId"):
      result.createdByUserId = to(node["createdByUserId"], string)
    if node.hasKey("createdAt"):
      result.createdAt = to(node["createdAt"], string)
    if node.hasKey("enabled"):
      result.enabled = to(node["enabled"], bool)
    if node.hasKey("urlId") and node["urlId"].kind != JNull:
      result.urlId = some(to(node["urlId"], typeof(result.urlId.get())))
    if node.hasKey("type"):
      result.`type` = to(node["type"], float64)
    if node.hasKey("threshold"):
      result.threshold = to(node["threshold"], float64)
    if node.hasKey("uses"):
      result.uses = to(node["uses"], float64)
    if node.hasKey("name"):
      result.name = to(node["name"], string)
    if node.hasKey("description"):
      result.description = to(node["description"], string)
    if node.hasKey("displayLabel"):
      result.displayLabel = to(node["displayLabel"], string)
    if node.hasKey("displaySrc") and node["displaySrc"].kind != JNull:
      result.displaySrc = some(to(node["displaySrc"], typeof(result.displaySrc.get())))
    if node.hasKey("backgroundColor") and node["backgroundColor"].kind != JNull:
      result.backgroundColor = some(to(node["backgroundColor"], typeof(result.backgroundColor.get())))
    if node.hasKey("borderColor") and node["borderColor"].kind != JNull:
      result.borderColor = some(to(node["borderColor"], typeof(result.borderColor.get())))
    if node.hasKey("textColor") and node["textColor"].kind != JNull:
      result.textColor = some(to(node["textColor"], typeof(result.textColor.get())))
    if node.hasKey("cssClass") and node["cssClass"].kind != JNull:
      result.cssClass = some(to(node["cssClass"], typeof(result.cssClass.get())))
    if node.hasKey("veteranUserThresholdMillis") and node["veteranUserThresholdMillis"].kind != JNull:
      result.veteranUserThresholdMillis = some(to(node["veteranUserThresholdMillis"], typeof(result.veteranUserThresholdMillis.get())))
    if node.hasKey("isAwaitingReprocess"):
      result.isAwaitingReprocess = to(node["isAwaitingReprocess"], bool)
    if node.hasKey("isAwaitingDeletion"):
      result.isAwaitingDeletion = to(node["isAwaitingDeletion"], bool)
    if node.hasKey("replacesBadgeId") and node["replacesBadgeId"].kind != JNull:
      result.replacesBadgeId = some(to(node["replacesBadgeId"], typeof(result.replacesBadgeId.get())))

# Custom JSON serialization for TenantBadge with custom field names
proc `%`*(obj: TenantBadge): JsonNode =
  result = newJObject()
  result["_id"] = %obj.id
  result["tenantId"] = %obj.tenantId
  result["createdByUserId"] = %obj.createdByUserId
  result["createdAt"] = %obj.createdAt
  result["enabled"] = %obj.enabled
  if obj.urlId.isSome():
    result["urlId"] = %obj.urlId.get()
  result["type"] = %obj.`type`
  result["threshold"] = %obj.threshold
  result["uses"] = %obj.uses
  result["name"] = %obj.name
  result["description"] = %obj.description
  result["displayLabel"] = %obj.displayLabel
  if obj.displaySrc.isSome():
    result["displaySrc"] = %obj.displaySrc.get()
  if obj.backgroundColor.isSome():
    result["backgroundColor"] = %obj.backgroundColor.get()
  if obj.borderColor.isSome():
    result["borderColor"] = %obj.borderColor.get()
  if obj.textColor.isSome():
    result["textColor"] = %obj.textColor.get()
  if obj.cssClass.isSome():
    result["cssClass"] = %obj.cssClass.get()
  if obj.veteranUserThresholdMillis.isSome():
    result["veteranUserThresholdMillis"] = %obj.veteranUserThresholdMillis.get()
  result["isAwaitingReprocess"] = %obj.isAwaitingReprocess
  result["isAwaitingDeletion"] = %obj.isAwaitingDeletion
  if obj.replacesBadgeId.isSome():
    result["replacesBadgeId"] = %obj.replacesBadgeId.get()

