#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_get_user_response
import model_user

# AnyOf type
type GetUserResponse1Kind* {.pure.} = enum
  GetUserResponseVariant
  APIErrorVariant

type GetUserResponse1* = object
  ## 
  case kind*: GetUserResponse1Kind
  of GetUserResponse1Kind.GetUserResponseVariant:
    GetUserResponseValue*: GetUserResponse
  of GetUserResponse1Kind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetUserResponse1]): GetUserResponse1 =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetUserResponse1(kind: GetUserResponse1Kind.GetUserResponseVariant, GetUserResponseValue: to(node, GetUserResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetUserResponse: ", e.msg
  try:
    return GetUserResponse1(kind: GetUserResponse1Kind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetUserResponse1. JSON: " & $node)

