#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_api_status

type CheckBlockedCommentsResponse* = object
  ## 
  commentStatuses*: Table[string, bool] ## Construct a type with a set of properties K of type T
  status*: APIStatus

