#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_moderation_api_comment
import model_moderation_filter
import model_object

type ModerationAPIGetCommentsResponse* = object
  ## 
  status*: APIStatus
  translations*: JsonNode
  comments*: seq[ModerationAPIComment]
  moderationFilter*: Option[ModerationFilter]


# Custom JSON deserialization for ModerationAPIGetCommentsResponse with custom field names
proc to*(node: JsonNode, T: typedesc[ModerationAPIGetCommentsResponse]): ModerationAPIGetCommentsResponse =
  result = ModerationAPIGetCommentsResponse()
  if node.kind == JObject:
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)
    if node.hasKey("translations"):
      result.translations = to(node["translations"], JsonNode)
    if node.hasKey("comments"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["comments"]
      if arrayNode.kind == JArray:
        result.comments = @[]
        for item in arrayNode.items:
          result.comments.add(to(item, ModerationAPIComment))
    if node.hasKey("moderationFilter") and node["moderationFilter"].kind != JNull:
      result.moderationFilter = some(to(node["moderationFilter"], typeof(result.moderationFilter.get())))

# Custom JSON serialization for ModerationAPIGetCommentsResponse with custom field names
proc `%`*(obj: ModerationAPIGetCommentsResponse): JsonNode =
  result = newJObject()
  result["status"] = %obj.status
  result["translations"] = %obj.translations
  result["comments"] = %obj.comments
  if obj.moderationFilter.isSome():
    result["moderationFilter"] = %obj.moderationFilter.get()

