#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_feed_post_stats
import model_feed_posts_stats_response

# AnyOf type
type GetFeedPostsStatsResponseKind* {.pure.} = enum
  FeedPostsStatsResponseVariant
  APIErrorVariant

type GetFeedPostsStatsResponse* = object
  ## 
  case kind*: GetFeedPostsStatsResponseKind
  of GetFeedPostsStatsResponseKind.FeedPostsStatsResponseVariant:
    FeedPostsStatsResponseValue*: FeedPostsStatsResponse
  of GetFeedPostsStatsResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetFeedPostsStatsResponse]): GetFeedPostsStatsResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetFeedPostsStatsResponse(kind: GetFeedPostsStatsResponseKind.FeedPostsStatsResponseVariant, FeedPostsStatsResponseValue: to(node, FeedPostsStatsResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as FeedPostsStatsResponse: ", e.msg
  try:
    return GetFeedPostsStatsResponse(kind: GetFeedPostsStatsResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetFeedPostsStatsResponse. JSON: " & $node)

