#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_gif_get_large_response

# AnyOf type
type GetGifLargeResponseKind* {.pure.} = enum
  GifGetLargeResponseVariant
  APIErrorVariant

type GetGifLargeResponse* = object
  ## 
  case kind*: GetGifLargeResponseKind
  of GetGifLargeResponseKind.GifGetLargeResponseVariant:
    GifGetLargeResponseValue*: GifGetLargeResponse
  of GetGifLargeResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetGifLargeResponse]): GetGifLargeResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetGifLargeResponse(kind: GetGifLargeResponseKind.GifGetLargeResponseVariant, GifGetLargeResponseValue: to(node, GifGetLargeResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GifGetLargeResponse: ", e.msg
  try:
    return GetGifLargeResponse(kind: GetGifLargeResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetGifLargeResponse. JSON: " & $node)

