#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_question_config

type CreateQuestionConfigResponse* = object
  ## 
  status*: APIStatus
  questionConfig*: QuestionConfig


# Custom JSON deserialization for CreateQuestionConfigResponse with custom field names
proc to*(node: JsonNode, T: typedesc[CreateQuestionConfigResponse]): CreateQuestionConfigResponse =
  result = CreateQuestionConfigResponse()
  if node.kind == JObject:
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)
    if node.hasKey("questionConfig"):
      result.questionConfig = to(node["questionConfig"], QuestionConfig)

# Custom JSON serialization for CreateQuestionConfigResponse with custom field names
proc `%`*(obj: CreateQuestionConfigResponse): JsonNode =
  result = newJObject()
  result["status"] = %obj.status
  result["questionConfig"] = %obj.questionConfig

