#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_delete_comment_action
import model_delete_comment_result

# AnyOf type
type DeleteCommentResponseKind* {.pure.} = enum
  DeleteCommentResultVariant
  APIErrorVariant

type DeleteCommentResponse* = object
  ## 
  case kind*: DeleteCommentResponseKind
  of DeleteCommentResponseKind.DeleteCommentResultVariant:
    DeleteCommentResultValue*: DeleteCommentResult
  of DeleteCommentResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[DeleteCommentResponse]): DeleteCommentResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return DeleteCommentResponse(kind: DeleteCommentResponseKind.DeleteCommentResultVariant, DeleteCommentResultValue: to(node, DeleteCommentResult))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as DeleteCommentResult: ", e.msg
  try:
    return DeleteCommentResponse(kind: DeleteCommentResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of DeleteCommentResponse. JSON: " & $node)

