#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_set_comment_approved_response

# AnyOf type
type PostSetCommentApprovalStatusResponseKind* {.pure.} = enum
  SetCommentApprovedResponseVariant
  APIErrorVariant

type PostSetCommentApprovalStatusResponse* = object
  ## 
  case kind*: PostSetCommentApprovalStatusResponseKind
  of PostSetCommentApprovalStatusResponseKind.SetCommentApprovedResponseVariant:
    SetCommentApprovedResponseValue*: SetCommentApprovedResponse
  of PostSetCommentApprovalStatusResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[PostSetCommentApprovalStatusResponse]): PostSetCommentApprovalStatusResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return PostSetCommentApprovalStatusResponse(kind: PostSetCommentApprovalStatusResponseKind.SetCommentApprovedResponseVariant, SetCommentApprovedResponseValue: to(node, SetCommentApprovedResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as SetCommentApprovedResponse: ", e.msg
  try:
    return PostSetCommentApprovalStatusResponse(kind: PostSetCommentApprovalStatusResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of PostSetCommentApprovalStatusResponse. JSON: " & $node)

