#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_api_tenant
import model_custom_config_parameters
import model_get_tenant_response

# AnyOf type
type GetTenant200responseKind* {.pure.} = enum
  GetTenantResponseVariant
  APIErrorVariant

type GetTenant200response* = object
  ## 
  case kind*: GetTenant200responseKind
  of GetTenant200responseKind.GetTenantResponseVariant:
    GetTenantResponseValue*: GetTenantResponse
  of GetTenant200responseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetTenant200response]): GetTenant200response =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetTenant200response(kind: GetTenant200responseKind.GetTenantResponseVariant, GetTenantResponseValue: to(node, GetTenantResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetTenantResponse: ", e.msg
  try:
    return GetTenant200response(kind: GetTenant200responseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetTenant200response. JSON: " & $node)

