#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type QuestionWhenSave* {.pure.} = enum
  `0`
  `1`

func `%`*(v: QuestionWhenSave): JsonNode =
  result = case v:
    of QuestionWhenSave.`0`: %(0)
    of QuestionWhenSave.`1`: %(1)

func `$`*(v: QuestionWhenSave): string =
  result = case v:
    of QuestionWhenSave.`0`: $(0)
    of QuestionWhenSave.`1`: $(1)
proc to*(node: JsonNode, T: typedesc[QuestionWhenSave]): QuestionWhenSave =
  if node.kind != JInt:
    raise newException(ValueError, "Expected integer for enum QuestionWhenSave, got " & $node.kind)
  let intVal = node.getInt()
  case intVal:
  of 0:
    return QuestionWhenSave.`0`
  of 1:
    return QuestionWhenSave.`1`
  else:
    raise newException(ValueError, "Invalid enum value for QuestionWhenSave: " & $intVal)

