#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_email_template_definition

type GetEmailTemplateDefinitionsResponse* = object
  ## 
  status*: APIStatus
  definitions*: seq[EmailTemplateDefinition]


# Custom JSON deserialization for GetEmailTemplateDefinitionsResponse with custom field names
proc to*(node: JsonNode, T: typedesc[GetEmailTemplateDefinitionsResponse]): GetEmailTemplateDefinitionsResponse =
  result = GetEmailTemplateDefinitionsResponse()
  if node.kind == JObject:
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)
    if node.hasKey("definitions"):
      result.definitions = to(node["definitions"], seq[EmailTemplateDefinition])

# Custom JSON serialization for GetEmailTemplateDefinitionsResponse with custom field names
proc `%`*(obj: GetEmailTemplateDefinitionsResponse): JsonNode =
  result = newJObject()
  result["status"] = %obj.status
  result["definitions"] = %obj.definitions

