#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_empty_response
import model_api_error
import model_api_status
import model_custom_config_parameters

# AnyOf type
type ReplaceTenantPackageResponseKind* {.pure.} = enum
  APIEmptyResponseVariant
  APIErrorVariant

type ReplaceTenantPackageResponse* = object
  ## 
  case kind*: ReplaceTenantPackageResponseKind
  of ReplaceTenantPackageResponseKind.APIEmptyResponseVariant:
    APIEmptyResponseValue*: APIEmptyResponse
  of ReplaceTenantPackageResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[ReplaceTenantPackageResponse]): ReplaceTenantPackageResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return ReplaceTenantPackageResponse(kind: ReplaceTenantPackageResponseKind.APIEmptyResponseVariant, APIEmptyResponseValue: to(node, APIEmptyResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIEmptyResponse: ", e.msg
  try:
    return ReplaceTenantPackageResponse(kind: ReplaceTenantPackageResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of ReplaceTenantPackageResponse. JSON: " & $node)

