#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_apisso_user

type AddSSOUserAPIResponse* = object
  ## 
  reason*: string
  code*: string
  user*: APISSOUser
  status*: string

