#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_question_config

type GetQuestionConfigsResponse* = object
  ## 
  status*: APIStatus
  questionConfigs*: seq[QuestionConfig]


# Custom JSON deserialization for GetQuestionConfigsResponse with custom field names
proc to*(node: JsonNode, T: typedesc[GetQuestionConfigsResponse]): GetQuestionConfigsResponse =
  result = GetQuestionConfigsResponse()
  if node.kind == JObject:
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)
    if node.hasKey("questionConfigs"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["questionConfigs"]
      if arrayNode.kind == JArray:
        result.questionConfigs = @[]
        for item in arrayNode.items:
          result.questionConfigs.add(to(item, QuestionConfig))

# Custom JSON serialization for GetQuestionConfigsResponse with custom field names
proc `%`*(obj: GetQuestionConfigsResponse): JsonNode =
  result = newJObject()
  result["status"] = %obj.status
  result["questionConfigs"] = %obj.questionConfigs

