#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_comment_user_badge_info

type PublicCommentBase* = object
  ## 
  id*: string
  userId*: string
  commenterName*: string
  commenterLink*: string
  commentHTML*: string
  parentId*: string
  date*: string
  votes*: int
  votesUp*: int
  votesDown*: int
  verified*: bool
  avatarSrc*: string
  hasImages*: bool
  isByAdmin*: bool
  isByModerator*: bool
  isPinned*: bool
  isLocked*: bool
  displayLabel*: string
  rating*: float64
  badges*: seq[CommentUserBadgeInfo]
  viewCount*: int64
  isDeleted*: bool
  isDeletedUser*: bool
  isSpam*: bool
  anonUserId*: string
  feedbackIds*: seq[string]
  requiresVerification*: bool
  editKey*: string

