#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_create_tenant_user_response
import model_custom_config_parameters
import model_user

# AnyOf type
type CreateTenantUserResponse1Kind* {.pure.} = enum
  CreateTenantUserResponseVariant
  APIErrorVariant

type CreateTenantUserResponse1* = object
  ## 
  case kind*: CreateTenantUserResponse1Kind
  of CreateTenantUserResponse1Kind.CreateTenantUserResponseVariant:
    CreateTenantUserResponseValue*: CreateTenantUserResponse
  of CreateTenantUserResponse1Kind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[CreateTenantUserResponse1]): CreateTenantUserResponse1 =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return CreateTenantUserResponse1(kind: CreateTenantUserResponse1Kind.CreateTenantUserResponseVariant, CreateTenantUserResponseValue: to(node, CreateTenantUserResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as CreateTenantUserResponse: ", e.msg
  try:
    return CreateTenantUserResponse1(kind: CreateTenantUserResponse1Kind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of CreateTenantUserResponse1. JSON: " & $node)

