#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type
import model_repeat_comment_check_ignored_reason
import model_repeat_comment_handling_action
import model_spam_rule

type PermanentFlag* {.pure.} = enum
  Permanent

type CommentLogData* = object
  ## 
  clearContent*: Option[bool]
  isDeletedUser*: Option[bool]
  phrase*: Option[string]
  badWord*: Option[string]
  word*: Option[string]
  locale*: Option[string]
  tenantBadgeId*: Option[string]
  badgeId*: Option[string]
  wasLoggedIn*: Option[bool]
  foundUser*: Option[bool]
  verified*: Option[bool]
  engine*: Option[string]
  engineResponse*: Option[string]
  engineTokens*: Option[float64]
  trustFactor*: Option[float64]
  rule*: Option[SpamRule]
  userId*: Option[string]
  subscribers*: Option[float64]
  notificationCount*: Option[float64]
  votesBefore*: Option[float64]
  votesUpBefore*: Option[float64]
  votesDownBefore*: Option[float64]
  votesAfter*: Option[float64]
  votesUpAfter*: Option[float64]
  votesDownAfter*: Option[float64]
  repeatAction*: Option[RepeatCommentHandlingAction]
  reason*: Option[RepeatCommentCheckIgnoredReason]
  otherData*: Option[JsonNode]
  spamBefore*: Option[bool]
  spamAfter*: Option[bool]
  permanentFlag*: Option[PermanentFlag]
  approvedBefore*: Option[bool]
  approvedAfter*: Option[bool]
  reviewedBefore*: Option[bool]
  reviewedAfter*: Option[bool]
  textBefore*: Option[string]
  textAfter*: Option[string]
  expireBefore*: Option[string]
  expireAfter*: Option[string]
  flagCountBefore*: Option[float64]
  trustFactorBefore*: Option[float64]
  trustFactorAfter*: Option[float64]
  referencedCommentId*: Option[string]
  invalidLocale*: Option[string]
  detectedLocale*: Option[string]
  detectedLanguage*: Option[string]

func `%`*(v: PermanentFlag): JsonNode =
  result = case v:
    of PermanentFlag.Permanent: %"permanent"
func `$`*(v: PermanentFlag): string =
  result = case v:
    of PermanentFlag.Permanent: $("permanent")

proc to*(node: JsonNode, T: typedesc[PermanentFlag]): PermanentFlag =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum PermanentFlag, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("permanent"):
    return PermanentFlag.Permanent
  else:
    raise newException(ValueError, "Invalid enum value for PermanentFlag: " & strVal)

