#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_add_domain_config200response_any_of
import model_any_type
import model_get_domain_configs200response_any_of1

type AddDomainConfig200response* = object
  ## 
  reason*: string
  code*: string
  status*: JsonNode
  configuration*: JsonNode

