#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ModerationUserSearchProjected* = object
  ## 
  id*: string
  username*: string
  displayName*: Option[string]
  avatarSrc*: Option[string]


# Custom JSON deserialization for ModerationUserSearchProjected with custom field names
proc to*(node: JsonNode, T: typedesc[ModerationUserSearchProjected]): ModerationUserSearchProjected =
  result = ModerationUserSearchProjected()
  if node.kind == JObject:
    if node.hasKey("_id"):
      result.id = to(node["_id"], string)
    if node.hasKey("username"):
      result.username = to(node["username"], string)
    if node.hasKey("displayName") and node["displayName"].kind != JNull:
      result.displayName = some(to(node["displayName"], typeof(result.displayName.get())))
    if node.hasKey("avatarSrc") and node["avatarSrc"].kind != JNull:
      result.avatarSrc = some(to(node["avatarSrc"], typeof(result.avatarSrc.get())))

# Custom JSON serialization for ModerationUserSearchProjected with custom field names
proc `%`*(obj: ModerationUserSearchProjected): JsonNode =
  result = newJObject()
  result["_id"] = %obj.id
  result["username"] = %obj.username
  if obj.displayName.isSome():
    result["displayName"] = %obj.displayName.get()
  if obj.avatarSrc.isSome():
    result["avatarSrc"] = %obj.avatarSrc.get()

