#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_create_v1_page_react
import model_custom_config_parameters

# AnyOf type
type CreateV2PageReactResponseKind* {.pure.} = enum
  CreateV2PageReactVariant
  APIErrorVariant

type CreateV2PageReactResponse* = object
  ## 
  case kind*: CreateV2PageReactResponseKind
  of CreateV2PageReactResponseKind.CreateV2PageReactVariant:
    CreateV2PageReactValue*: CreateV1PageReact
  of CreateV2PageReactResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[CreateV2PageReactResponse]): CreateV2PageReactResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return CreateV2PageReactResponse(kind: CreateV2PageReactResponseKind.CreateV2PageReactVariant, CreateV2PageReactValue: to(node, CreateV1PageReact))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as CreateV1PageReact: ", e.msg
  try:
    return CreateV2PageReactResponse(kind: CreateV2PageReactResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of CreateV2PageReactResponse. JSON: " & $node)

