#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_create_feed_post_response
import model_custom_config_parameters
import model_feed_post

# AnyOf type
type UpdateFeedPostPublicResponseKind* {.pure.} = enum
  CreateFeedPostResponseVariant
  APIErrorVariant

type UpdateFeedPostPublicResponse* = object
  ## 
  case kind*: UpdateFeedPostPublicResponseKind
  of UpdateFeedPostPublicResponseKind.CreateFeedPostResponseVariant:
    CreateFeedPostResponseValue*: CreateFeedPostResponse
  of UpdateFeedPostPublicResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[UpdateFeedPostPublicResponse]): UpdateFeedPostPublicResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return UpdateFeedPostPublicResponse(kind: UpdateFeedPostPublicResponseKind.CreateFeedPostResponseVariant, CreateFeedPostResponseValue: to(node, CreateFeedPostResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as CreateFeedPostResponse: ", e.msg
  try:
    return UpdateFeedPostPublicResponse(kind: UpdateFeedPostPublicResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of UpdateFeedPostPublicResponse. JSON: " & $node)

