#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_moderation_api_comment

type ModerationAPIChildCommentsResponse* = object
  ## 
  comments*: seq[ModerationAPIComment]
  status*: APIStatus


# Custom JSON deserialization for ModerationAPIChildCommentsResponse with custom field names
proc to*(node: JsonNode, T: typedesc[ModerationAPIChildCommentsResponse]): ModerationAPIChildCommentsResponse =
  result = ModerationAPIChildCommentsResponse()
  if node.kind == JObject:
    if node.hasKey("comments"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["comments"]
      if arrayNode.kind == JArray:
        result.comments = @[]
        for item in arrayNode.items:
          result.comments.add(to(item, ModerationAPIComment))
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)

# Custom JSON serialization for ModerationAPIChildCommentsResponse with custom field names
proc `%`*(obj: ModerationAPIChildCommentsResponse): JsonNode =
  result = newJObject()
  result["comments"] = %obj.comments
  result["status"] = %obj.status

