#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type PublicBlockFromCommentParams* = object
  ## 
  commentIds*: Option[seq[string]] ## A list of comment ids to check if are blocked after performing the update.

