#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_ignored_response
import model_user_notification_write_response

# AnyOf type
type UpdateUserNotificationPageSubscriptionStatusResponseKind* {.pure.} = enum
  UserNotificationWriteResponseVariant
  IgnoredResponseVariant

type UpdateUserNotificationPageSubscriptionStatusResponse* = object
  ## 
  case kind*: UpdateUserNotificationPageSubscriptionStatusResponseKind
  of UpdateUserNotificationPageSubscriptionStatusResponseKind.UserNotificationWriteResponseVariant:
    UserNotificationWriteResponseValue*: UserNotificationWriteResponse
  of UpdateUserNotificationPageSubscriptionStatusResponseKind.IgnoredResponseVariant:
    IgnoredResponseValue*: IgnoredResponse

proc to*(node: JsonNode, T: typedesc[UpdateUserNotificationPageSubscriptionStatusResponse]): UpdateUserNotificationPageSubscriptionStatusResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return UpdateUserNotificationPageSubscriptionStatusResponse(kind: UpdateUserNotificationPageSubscriptionStatusResponseKind.UserNotificationWriteResponseVariant, UserNotificationWriteResponseValue: to(node, UserNotificationWriteResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as UserNotificationWriteResponse: ", e.msg
  try:
    return UpdateUserNotificationPageSubscriptionStatusResponse(kind: UpdateUserNotificationPageSubscriptionStatusResponseKind.IgnoredResponseVariant, IgnoredResponseValue: to(node, IgnoredResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as IgnoredResponse: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of UpdateUserNotificationPageSubscriptionStatusResponse. JSON: " & $node)

