#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_record_string_before_string_or_null_after_string_or_null_value

type LiveEventExtraInfo* = object
  ## 
  commentPositions*: Option[Table[string, RecordStringBeforeStringOrNullAfterStringOrNullValue]] ## Construct a type with a set of properties K of type T


# Custom JSON deserialization for LiveEventExtraInfo with custom field names
proc to*(node: JsonNode, T: typedesc[LiveEventExtraInfo]): LiveEventExtraInfo =
  result = LiveEventExtraInfo()
  if node.kind == JObject:
    if node.hasKey("commentPositions") and node["commentPositions"].kind != JNull:
      result.commentPositions = some(to(node["commentPositions"], typeof(result.commentPositions.get())))

# Custom JSON serialization for LiveEventExtraInfo with custom field names
proc `%`*(obj: LiveEventExtraInfo): JsonNode =
  result = newJObject()
  if obj.commentPositions.isSome():
    result["commentPositions"] = %obj.commentPositions.get()

