#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ImportedSiteType* {.pure.} = enum
  `0`
  `1`

func `%`*(v: ImportedSiteType): JsonNode =
  result = case v:
    of ImportedSiteType.`0`: %(0)
    of ImportedSiteType.`1`: %(1)

func `$`*(v: ImportedSiteType): string =
  result = case v:
    of ImportedSiteType.`0`: $(0)
    of ImportedSiteType.`1`: $(1)
proc to*(node: JsonNode, T: typedesc[ImportedSiteType]): ImportedSiteType =
  if node.kind != JInt:
    raise newException(ValueError, "Expected integer for enum ImportedSiteType, got " & $node.kind)
  let intVal = node.getInt()
  case intVal:
  of 0:
    return ImportedSiteType.`0`
  of 1:
    return ImportedSiteType.`1`
  else:
    raise newException(ValueError, "Invalid enum value for ImportedSiteType: " & $intVal)

