#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_gif_search_internal_error
import model_gif_search_response
import model_gif_search_response_images_inner_inner

# AnyOf type
type GetGifsTrendingResponseKind* {.pure.} = enum
  GifSearchResponseVariant
  GifSearchInternalErrorVariant

type GetGifsTrendingResponse* = object
  ## 
  case kind*: GetGifsTrendingResponseKind
  of GetGifsTrendingResponseKind.GifSearchResponseVariant:
    GifSearchResponseValue*: GifSearchResponse
  of GetGifsTrendingResponseKind.GifSearchInternalErrorVariant:
    GifSearchInternalErrorValue*: GifSearchInternalError

proc to*(node: JsonNode, T: typedesc[GetGifsTrendingResponse]): GetGifsTrendingResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetGifsTrendingResponse(kind: GetGifsTrendingResponseKind.GifSearchResponseVariant, GifSearchResponseValue: to(node, GifSearchResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GifSearchResponse: ", e.msg
  try:
    return GetGifsTrendingResponse(kind: GetGifsTrendingResponseKind.GifSearchInternalErrorVariant, GifSearchInternalErrorValue: to(node, GifSearchInternalError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GifSearchInternalError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetGifsTrendingResponse. JSON: " & $node)

