#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_get_user_badge_progress_response
import model_api_status
import model_custom_config_parameters
import model_user_badge_progress

# AnyOf type
type GetUserBadgeProgressByUserIdResponseKind* {.pure.} = enum
  APIGetUserBadgeProgressResponseVariant
  APIErrorVariant

type GetUserBadgeProgressByUserIdResponse* = object
  ## 
  case kind*: GetUserBadgeProgressByUserIdResponseKind
  of GetUserBadgeProgressByUserIdResponseKind.APIGetUserBadgeProgressResponseVariant:
    APIGetUserBadgeProgressResponseValue*: APIGetUserBadgeProgressResponse
  of GetUserBadgeProgressByUserIdResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetUserBadgeProgressByUserIdResponse]): GetUserBadgeProgressByUserIdResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetUserBadgeProgressByUserIdResponse(kind: GetUserBadgeProgressByUserIdResponseKind.APIGetUserBadgeProgressResponseVariant, APIGetUserBadgeProgressResponseValue: to(node, APIGetUserBadgeProgressResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIGetUserBadgeProgressResponse: ", e.msg
  try:
    return GetUserBadgeProgressByUserIdResponse(kind: GetUserBadgeProgressByUserIdResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetUserBadgeProgressByUserIdResponse. JSON: " & $node)

