#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_get_pending_webhook_event_count_response

# AnyOf type
type GetPendingWebhookEventCountResponse1Kind* {.pure.} = enum
  GetPendingWebhookEventCountResponseVariant
  APIErrorVariant

type GetPendingWebhookEventCountResponse1* = object
  ## 
  case kind*: GetPendingWebhookEventCountResponse1Kind
  of GetPendingWebhookEventCountResponse1Kind.GetPendingWebhookEventCountResponseVariant:
    GetPendingWebhookEventCountResponseValue*: GetPendingWebhookEventCountResponse
  of GetPendingWebhookEventCountResponse1Kind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetPendingWebhookEventCountResponse1]): GetPendingWebhookEventCountResponse1 =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetPendingWebhookEventCountResponse1(kind: GetPendingWebhookEventCountResponse1Kind.GetPendingWebhookEventCountResponseVariant, GetPendingWebhookEventCountResponseValue: to(node, GetPendingWebhookEventCountResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetPendingWebhookEventCountResponse: ", e.msg
  try:
    return GetPendingWebhookEventCountResponse1(kind: GetPendingWebhookEventCountResponse1Kind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetPendingWebhookEventCountResponse1. JSON: " & $node)

