#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_feed_post_link
import model_feed_post_media_item

type CreateFeedPostParams* = object
  ## 
  title*: Option[string]
  contentHTML*: Option[string]
  media*: Option[seq[FeedPostMediaItem]]
  links*: Option[seq[FeedPostLink]]
  fromUserId*: Option[string]
  fromUserDisplayName*: Option[string]
  tags*: Option[seq[string]]
  meta*: Option[Table[string, string]] ## Construct a type with a set of properties K of type T

