#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_gif_search_response_images_inner_inner

type GifSearchResponse* = object
  ## 
  images*: seq[seq[GifSearchResponse_images_inner_inner]]
  status*: APIStatus

