#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type SortDirections* {.pure.} = enum
  OF
  NF
  MR

func `%`*(v: SortDirections): JsonNode =
  result = case v:
    of SortDirections.OF: %"OF"
    of SortDirections.NF: %"NF"
    of SortDirections.MR: %"MR"

func `$`*(v: SortDirections): string =
  result = case v:
    of SortDirections.OF: $("OF")
    of SortDirections.NF: $("NF")
    of SortDirections.MR: $("MR")

proc to*(node: JsonNode, T: typedesc[SortDirections]): SortDirections =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum SortDirections, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("OF"):
    return SortDirections.OF
  of $("NF"):
    return SortDirections.NF
  of $("MR"):
    return SortDirections.MR
  else:
    raise newException(ValueError, "Invalid enum value for SortDirections: " & strVal)
