#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_search_users_response
import model_user_search_result

type SearchUsers200response* = object
  ## 
  status*: APIStatus
  users*: seq[UserSearchResult]
  reason*: string
  code*: string
  secondaryCode*: string
  bannedUntil*: int64
  maxCharacterLength*: int
  translatedError*: string
  customConfig*: CustomConfigParameters

