#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_notification_object_type
import model_notification_type

type RenderableUserNotification* = object
  ## 
  conversationId*: string
  contextHTML*: string
  fromUserNames*: seq[string]
  fromUserIds*: seq[string]
  relatedIds*: seq[string]
  count*: int64
  optedOut*: bool
  fromUserAvatarSrc*: string
  fromUserId*: string
  fromUserName*: string
  fromCommentId*: string
  `type`*: NotificationType
  createdAt*: string
  sent*: string
  viewed*: string
  relatedObjectId*: string
  relatedObjectType*: NotificationObjectType
  pageTitle*: string
  url*: string
  urlId*: string
  id*: string

