#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_change_comment_pin_status_response
import model_custom_config_parameters
import model_record_string_before_string_or_null_after_string_or_null_value

# AnyOf type
type UnPinCommentResponseKind* {.pure.} = enum
  ChangeCommentPinStatusResponseVariant
  APIErrorVariant

type UnPinCommentResponse* = object
  ## 
  case kind*: UnPinCommentResponseKind
  of UnPinCommentResponseKind.ChangeCommentPinStatusResponseVariant:
    ChangeCommentPinStatusResponseValue*: ChangeCommentPinStatusResponse
  of UnPinCommentResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[UnPinCommentResponse]): UnPinCommentResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return UnPinCommentResponse(kind: UnPinCommentResponseKind.ChangeCommentPinStatusResponseVariant, ChangeCommentPinStatusResponseValue: to(node, ChangeCommentPinStatusResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as ChangeCommentPinStatusResponse: ", e.msg
  try:
    return UnPinCommentResponse(kind: UnPinCommentResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of UnPinCommentResponse. JSON: " & $node)

