#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_moderate_get_user_ban_preferences_response
import model_api_moderate_user_ban_preferences
import model_api_status
import model_custom_config_parameters

# AnyOf type
type GetUserBanPreferenceResponseKind* {.pure.} = enum
  APIModerateGetUserBanPreferencesResponseVariant
  APIErrorVariant

type GetUserBanPreferenceResponse* = object
  ## 
  case kind*: GetUserBanPreferenceResponseKind
  of GetUserBanPreferenceResponseKind.APIModerateGetUserBanPreferencesResponseVariant:
    APIModerateGetUserBanPreferencesResponseValue*: APIModerateGetUserBanPreferencesResponse
  of GetUserBanPreferenceResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetUserBanPreferenceResponse]): GetUserBanPreferenceResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetUserBanPreferenceResponse(kind: GetUserBanPreferenceResponseKind.APIModerateGetUserBanPreferencesResponseVariant, APIModerateGetUserBanPreferencesResponseValue: to(node, APIModerateGetUserBanPreferencesResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIModerateGetUserBanPreferencesResponse: ", e.msg
  try:
    return GetUserBanPreferenceResponse(kind: GetUserBanPreferenceResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetUserBanPreferenceResponse. JSON: " & $node)

