#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_event_log_entry

type GetEventLogResponse* = object
  ## 
  events*: seq[EventLogEntry]
  status*: APIStatus


# Custom JSON deserialization for GetEventLogResponse with custom field names
proc to*(node: JsonNode, T: typedesc[GetEventLogResponse]): GetEventLogResponse =
  result = GetEventLogResponse()
  if node.kind == JObject:
    if node.hasKey("events"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["events"]
      if arrayNode.kind == JArray:
        result.events = @[]
        for item in arrayNode.items:
          result.events.add(to(item, EventLogEntry))
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)

# Custom JSON serialization for GetEventLogResponse with custom field names
proc `%`*(obj: GetEventLogResponse): JsonNode =
  result = newJObject()
  result["events"] = %obj.events
  result["status"] = %obj.status

