#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_object
import model_public_comment
import model_save_comments_response_with_presence
import model_user_session_info

# AnyOf type
type CreateCommentPublic200responseKind* {.pure.} = enum
  SaveCommentsResponseWithPresenceVariant
  APIErrorVariant

type CreateCommentPublic200response* = object
  ## 
  case kind*: CreateCommentPublic200responseKind
  of CreateCommentPublic200responseKind.SaveCommentsResponseWithPresenceVariant:
    SaveCommentsResponseWithPresenceValue*: SaveCommentsResponseWithPresence
  of CreateCommentPublic200responseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[CreateCommentPublic200response]): CreateCommentPublic200response =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return CreateCommentPublic200response(kind: CreateCommentPublic200responseKind.SaveCommentsResponseWithPresenceVariant, SaveCommentsResponseWithPresenceValue: to(node, SaveCommentsResponseWithPresence))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as SaveCommentsResponseWithPresence: ", e.msg
  try:
    return CreateCommentPublic200response(kind: CreateCommentPublic200responseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of CreateCommentPublic200response. JSON: " & $node)
