#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables


type UserBadge* = object
  ## 
  id*: string
  userId*: string
  badgeId*: string
  fromTenantId*: string
  createdAt*: string
  `type`*: int
  threshold*: int64
  description*: string
  displayLabel*: string
  displaySrc*: string
  backgroundColor*: string
  borderColor*: string
  textColor*: string
  cssClass*: string
  veteranUserThresholdMillis*: int64
  displayedOnComments*: bool
  receivedAt*: string
  order*: int

