#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_aggregation_value

type AggregationItem* = object
  ## 
  groups*: Table[string, string] ## Construct a type with a set of properties K of type T

