#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_feed_post
import model_get_feed_posts_response

# AnyOf type
type GetFeedPostsResponse1Kind* {.pure.} = enum
  GetFeedPostsResponseVariant
  APIErrorVariant

type GetFeedPostsResponse1* = object
  ## 
  case kind*: GetFeedPostsResponse1Kind
  of GetFeedPostsResponse1Kind.GetFeedPostsResponseVariant:
    GetFeedPostsResponseValue*: GetFeedPostsResponse
  of GetFeedPostsResponse1Kind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetFeedPostsResponse1]): GetFeedPostsResponse1 =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetFeedPostsResponse1(kind: GetFeedPostsResponse1Kind.GetFeedPostsResponseVariant, GetFeedPostsResponseValue: to(node, GetFeedPostsResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetFeedPostsResponse: ", e.msg
  try:
    return GetFeedPostsResponse1(kind: GetFeedPostsResponse1Kind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetFeedPostsResponse1. JSON: " & $node)

