#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_pending_comment_to_sync_outbound

type GetPendingWebhookEventsResponse* = object
  ## 
  status*: APIStatus
  pendingWebhookEvents*: seq[PendingCommentToSyncOutbound]


# Custom JSON deserialization for GetPendingWebhookEventsResponse with custom field names
proc to*(node: JsonNode, T: typedesc[GetPendingWebhookEventsResponse]): GetPendingWebhookEventsResponse =
  result = GetPendingWebhookEventsResponse()
  if node.kind == JObject:
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)
    if node.hasKey("pendingWebhookEvents"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["pendingWebhookEvents"]
      if arrayNode.kind == JArray:
        result.pendingWebhookEvents = @[]
        for item in arrayNode.items:
          result.pendingWebhookEvents.add(to(item, PendingCommentToSyncOutbound))

# Custom JSON serialization for GetPendingWebhookEventsResponse with custom field names
proc `%`*(obj: GetPendingWebhookEventsResponse): JsonNode =
  result = newJObject()
  result["status"] = %obj.status
  result["pendingWebhookEvents"] = %obj.pendingWebhookEvents

