#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_question_config_custom_options_inner

type QuestionConfig* = object
  ## 
  id*: string
  tenantId*: string
  name*: string
  question*: string
  summaryLabel*: Option[string]
  helpText*: string
  createdAt*: string
  createdBy*: string
  usedCount*: float64
  lastUsed*: string
  `type`*: string
  numStars*: float64
  min*: float64
  max*: float64
  defaultValue*: float64
  labelNegative*: string
  labelPositive*: string
  customOptions*: seq[QuestionConfig_customOptions_inner]
  subQuestionIds*: seq[string]
  alwaysShowSubQuestions*: bool
  reportingOrder*: float64


# Custom JSON deserialization for QuestionConfig with custom field names
proc to*(node: JsonNode, T: typedesc[QuestionConfig]): QuestionConfig =
  result = QuestionConfig()
  if node.kind == JObject:
    if node.hasKey("_id"):
      result.id = to(node["_id"], string)
    if node.hasKey("tenantId"):
      result.tenantId = to(node["tenantId"], string)
    if node.hasKey("name"):
      result.name = to(node["name"], string)
    if node.hasKey("question"):
      result.question = to(node["question"], string)
    if node.hasKey("summaryLabel") and node["summaryLabel"].kind != JNull:
      result.summaryLabel = some(to(node["summaryLabel"], typeof(result.summaryLabel.get())))
    if node.hasKey("helpText"):
      result.helpText = to(node["helpText"], string)
    if node.hasKey("createdAt"):
      result.createdAt = to(node["createdAt"], string)
    if node.hasKey("createdBy"):
      result.createdBy = to(node["createdBy"], string)
    if node.hasKey("usedCount"):
      result.usedCount = to(node["usedCount"], float64)
    if node.hasKey("lastUsed"):
      result.lastUsed = to(node["lastUsed"], string)
    if node.hasKey("type"):
      result.`type` = to(node["type"], string)
    if node.hasKey("numStars"):
      result.numStars = to(node["numStars"], float64)
    if node.hasKey("min"):
      result.min = to(node["min"], float64)
    if node.hasKey("max"):
      result.max = to(node["max"], float64)
    if node.hasKey("defaultValue"):
      result.defaultValue = to(node["defaultValue"], float64)
    if node.hasKey("labelNegative"):
      result.labelNegative = to(node["labelNegative"], string)
    if node.hasKey("labelPositive"):
      result.labelPositive = to(node["labelPositive"], string)
    if node.hasKey("customOptions"):
      result.customOptions = to(node["customOptions"], seq[QuestionConfig_customOptions_inner])
    if node.hasKey("subQuestionIds"):
      result.subQuestionIds = to(node["subQuestionIds"], seq[string])
    if node.hasKey("alwaysShowSubQuestions"):
      result.alwaysShowSubQuestions = to(node["alwaysShowSubQuestions"], bool)
    if node.hasKey("reportingOrder"):
      result.reportingOrder = to(node["reportingOrder"], float64)

# Custom JSON serialization for QuestionConfig with custom field names
proc `%`*(obj: QuestionConfig): JsonNode =
  result = newJObject()
  result["_id"] = %obj.id
  result["tenantId"] = %obj.tenantId
  result["name"] = %obj.name
  result["question"] = %obj.question
  if obj.summaryLabel.isSome():
    result["summaryLabel"] = %obj.summaryLabel.get()
  result["helpText"] = %obj.helpText
  result["createdAt"] = %obj.createdAt
  result["createdBy"] = %obj.createdBy
  result["usedCount"] = %obj.usedCount
  result["lastUsed"] = %obj.lastUsed
  result["type"] = %obj.`type`
  result["numStars"] = %obj.numStars
  result["min"] = %obj.min
  result["max"] = %obj.max
  result["defaultValue"] = %obj.defaultValue
  result["labelNegative"] = %obj.labelNegative
  result["labelPositive"] = %obj.labelPositive
  result["customOptions"] = %obj.customOptions
  result["subQuestionIds"] = %obj.subQuestionIds
  result["alwaysShowSubQuestions"] = %obj.alwaysShowSubQuestions
  result["reportingOrder"] = %obj.reportingOrder

