#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_add_hash_tag200response
import model_api_status

type BulkCreateHashTagsResponse* = object
  ## 
  status*: APIStatus
  results*: seq[AddHashTag_200_response]

