#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_api_status
import model_notification_and_count
import model_object

type HeaderState* = object
  ## 
  status*: APIStatus
  notificationType*: JsonNode
  userId*: string
  userIdWS*: string
  notificationCounts*: seq[NotificationAndCount]

