#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type SizePreset* {.pure.} = enum
  Default
  CrossPlatform

func `%`*(v: SizePreset): JsonNode =
  result = case v:
    of SizePreset.Default: %"Default"
    of SizePreset.CrossPlatform: %"CrossPlatform"

func `$`*(v: SizePreset): string =
  result = case v:
    of SizePreset.Default: $("Default")
    of SizePreset.CrossPlatform: $("CrossPlatform")

proc to*(node: JsonNode, T: typedesc[SizePreset]): SizePreset =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum SizePreset, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("Default"):
    return SizePreset.Default
  of $("CrossPlatform"):
    return SizePreset.CrossPlatform
  else:
    raise newException(ValueError, "Invalid enum value for SizePreset: " & strVal)

