#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_bulk_create_hash_tags_response
import model_bulk_create_hash_tags_response_results_inner
import model_custom_config_parameters

# AnyOf type
type AddHashTagsBulkResponseKind* {.pure.} = enum
  BulkCreateHashTagsResponseVariant
  APIErrorVariant

type AddHashTagsBulkResponse* = object
  ## 
  case kind*: AddHashTagsBulkResponseKind
  of AddHashTagsBulkResponseKind.BulkCreateHashTagsResponseVariant:
    BulkCreateHashTagsResponseValue*: BulkCreateHashTagsResponse
  of AddHashTagsBulkResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[AddHashTagsBulkResponse]): AddHashTagsBulkResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return AddHashTagsBulkResponse(kind: AddHashTagsBulkResponseKind.BulkCreateHashTagsResponseVariant, BulkCreateHashTagsResponseValue: to(node, BulkCreateHashTagsResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as BulkCreateHashTagsResponse: ", e.msg
  try:
    return AddHashTagsBulkResponse(kind: AddHashTagsBulkResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of AddHashTagsBulkResponse. JSON: " & $node)

