#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_tenant_hash_tag

type GetHashTagsResponse* = object
  ## 
  status*: APIStatus
  hashTags*: seq[TenantHashTag]


# Custom JSON deserialization for GetHashTagsResponse with custom field names
proc to*(node: JsonNode, T: typedesc[GetHashTagsResponse]): GetHashTagsResponse =
  result = GetHashTagsResponse()
  if node.kind == JObject:
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)
    if node.hasKey("hashTags"):
      # Array of types with custom JSON - manually iterate and deserialize
      let arrayNode = node["hashTags"]
      if arrayNode.kind == JArray:
        result.hashTags = @[]
        for item in arrayNode.items:
          result.hashTags.add(to(item, TenantHashTag))

# Custom JSON serialization for GetHashTagsResponse with custom field names
proc `%`*(obj: GetHashTagsResponse): JsonNode =
  result = newJObject()
  result["status"] = %obj.status
  result["hashTags"] = %obj.hashTags

