#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type SORTDIR* {.pure.} = enum
  ASC
  DESC

func `%`*(v: SORTDIR): JsonNode =
  result = case v:
    of SORTDIR.ASC: %"ASC"
    of SORTDIR.DESC: %"DESC"

func `$`*(v: SORTDIR): string =
  result = case v:
    of SORTDIR.ASC: $("ASC")
    of SORTDIR.DESC: $("DESC")

proc to*(node: JsonNode, T: typedesc[SORTDIR]): SORTDIR =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum SORTDIR, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("ASC"):
    return SORTDIR.ASC
  of $("DESC"):
    return SORTDIR.DESC
  else:
    raise newException(ValueError, "Invalid enum value for SORTDIR: " & strVal)
