#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_api_status
import model_renderable_user_notification

type GetMyNotificationsResponse* = object
  ## 
  translations*: Table[string, string] ## Construct a type with a set of properties K of type T
  isSubscribed*: bool
  hasMore*: bool
  notifications*: seq[RenderableUserNotification]
  status*: APIStatus

