#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_create_hash_tag_response
import model_custom_config_parameters
import model_tenant_hash_tag

# AnyOf type
type AddHashTagResponseKind* {.pure.} = enum
  CreateHashTagResponseVariant
  APIErrorVariant

type AddHashTagResponse* = object
  ## 
  case kind*: AddHashTagResponseKind
  of AddHashTagResponseKind.CreateHashTagResponseVariant:
    CreateHashTagResponseValue*: CreateHashTagResponse
  of AddHashTagResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[AddHashTagResponse]): AddHashTagResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return AddHashTagResponse(kind: AddHashTagResponseKind.CreateHashTagResponseVariant, CreateHashTagResponseValue: to(node, CreateHashTagResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as CreateHashTagResponse: ", e.msg
  try:
    return AddHashTagResponse(kind: AddHashTagResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of AddHashTagResponse. JSON: " & $node)

