#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type

type EmailTemplateDefinition* = object
  ## 
  emailTemplateId*: string
  defaultTestData*: Table[string, JsonNode] ## Construct a type with a set of properties K of type T
  defaultTranslationsByLocale*: Table[string, Table[string, string]] ## Construct a type with a set of properties K of type T
  defaultEJS*: string

