#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_check_blocked_comments_response
import model_custom_config_parameters

# AnyOf type
type CheckedCommentsForBlockedResponseKind* {.pure.} = enum
  CheckBlockedCommentsResponseVariant
  APIErrorVariant

type CheckedCommentsForBlockedResponse* = object
  ## 
  case kind*: CheckedCommentsForBlockedResponseKind
  of CheckedCommentsForBlockedResponseKind.CheckBlockedCommentsResponseVariant:
    CheckBlockedCommentsResponseValue*: CheckBlockedCommentsResponse
  of CheckedCommentsForBlockedResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[CheckedCommentsForBlockedResponse]): CheckedCommentsForBlockedResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return CheckedCommentsForBlockedResponse(kind: CheckedCommentsForBlockedResponseKind.CheckBlockedCommentsResponseVariant, CheckBlockedCommentsResponseValue: to(node, CheckBlockedCommentsResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as CheckBlockedCommentsResponse: ", e.msg
  try:
    return CheckedCommentsForBlockedResponse(kind: CheckedCommentsForBlockedResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of CheckedCommentsForBlockedResponse. JSON: " & $node)

