#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_banned_user_match_matched_on_value
import model_banned_user_match_type

type BannedUserMatch* = object
  ## 
  matchedOn*: BannedUserMatchType
  matchedOnValue*: Option[BannedUserMatchMatchedOnValue]


# Custom JSON deserialization for BannedUserMatch with custom field names
proc to*(node: JsonNode, T: typedesc[BannedUserMatch]): BannedUserMatch =
  result = BannedUserMatch()
  if node.kind == JObject:
    if node.hasKey("matchedOn"):
      result.matchedOn = to(node["matchedOn"], BannedUserMatchType)
    if node.hasKey("matchedOnValue") and node["matchedOnValue"].kind != JNull:
      result.matchedOnValue = some(to(node["matchedOnValue"], typeof(result.matchedOnValue.get())))

# Custom JSON serialization for BannedUserMatch with custom field names
proc `%`*(obj: BannedUserMatch): JsonNode =
  result = newJObject()
  result["matchedOn"] = %obj.matchedOn
  if obj.matchedOnValue.isSome():
    result["matchedOnValue"] = %obj.matchedOnValue.get()

