#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_f_comment
import model_object

type PendingCommentToSyncOutbound* = object
  ## 
  id*: string
  commentId*: string
  comment*: Option[FComment]
  externalId*: Option[string]
  createdAt*: string
  tenantId*: string
  attemptCount*: float64
  nextAttemptAt*: string
  eventType*: float64
  `type`*: float64
  domain*: string
  lastError*: JsonNode
  webhookId*: Option[string]


# Custom JSON deserialization for PendingCommentToSyncOutbound with custom field names
proc to*(node: JsonNode, T: typedesc[PendingCommentToSyncOutbound]): PendingCommentToSyncOutbound =
  result = PendingCommentToSyncOutbound()
  if node.kind == JObject:
    if node.hasKey("_id"):
      result.id = to(node["_id"], string)
    if node.hasKey("commentId"):
      result.commentId = to(node["commentId"], string)
    if node.hasKey("comment") and node["comment"].kind != JNull:
      result.comment = some(to(node["comment"], typeof(result.comment.get())))
    if node.hasKey("externalId") and node["externalId"].kind != JNull:
      result.externalId = some(to(node["externalId"], typeof(result.externalId.get())))
    if node.hasKey("createdAt"):
      result.createdAt = to(node["createdAt"], string)
    if node.hasKey("tenantId"):
      result.tenantId = to(node["tenantId"], string)
    if node.hasKey("attemptCount"):
      result.attemptCount = to(node["attemptCount"], float64)
    if node.hasKey("nextAttemptAt"):
      result.nextAttemptAt = to(node["nextAttemptAt"], string)
    if node.hasKey("eventType"):
      result.eventType = to(node["eventType"], float64)
    if node.hasKey("type"):
      result.`type` = to(node["type"], float64)
    if node.hasKey("domain"):
      result.domain = to(node["domain"], string)
    if node.hasKey("lastError"):
      result.lastError = to(node["lastError"], JsonNode)
    if node.hasKey("webhookId") and node["webhookId"].kind != JNull:
      result.webhookId = some(to(node["webhookId"], typeof(result.webhookId.get())))

# Custom JSON serialization for PendingCommentToSyncOutbound with custom field names
proc `%`*(obj: PendingCommentToSyncOutbound): JsonNode =
  result = newJObject()
  result["_id"] = %obj.id
  result["commentId"] = %obj.commentId
  if obj.comment.isSome():
    result["comment"] = %obj.comment.get()
  if obj.externalId.isSome():
    result["externalId"] = %obj.externalId.get()
  result["createdAt"] = %obj.createdAt
  result["tenantId"] = %obj.tenantId
  result["attemptCount"] = %obj.attemptCount
  result["nextAttemptAt"] = %obj.nextAttemptAt
  result["eventType"] = %obj.eventType
  result["type"] = %obj.`type`
  result["domain"] = %obj.domain
  result["lastError"] = %obj.lastError
  if obj.webhookId.isSome():
    result["webhookId"] = %obj.webhookId.get()

