#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_get_comment_text_response

# AnyOf type
type GetModerationCommentTextResponseKind* {.pure.} = enum
  GetCommentTextResponseVariant
  APIErrorVariant

type GetModerationCommentTextResponse* = object
  ## 
  case kind*: GetModerationCommentTextResponseKind
  of GetModerationCommentTextResponseKind.GetCommentTextResponseVariant:
    GetCommentTextResponseValue*: GetCommentTextResponse
  of GetModerationCommentTextResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetModerationCommentTextResponse]): GetModerationCommentTextResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetModerationCommentTextResponse(kind: GetModerationCommentTextResponseKind.GetCommentTextResponseVariant, GetCommentTextResponseValue: to(node, GetCommentTextResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetCommentTextResponse: ", e.msg
  try:
    return GetModerationCommentTextResponse(kind: GetModerationCommentTextResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetModerationCommentTextResponse. JSON: " & $node)

