#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_create_question_config_response
import model_custom_config_parameters
import model_question_config

# AnyOf type
type CreateQuestionConfigResponse1Kind* {.pure.} = enum
  CreateQuestionConfigResponseVariant
  APIErrorVariant

type CreateQuestionConfigResponse1* = object
  ## 
  case kind*: CreateQuestionConfigResponse1Kind
  of CreateQuestionConfigResponse1Kind.CreateQuestionConfigResponseVariant:
    CreateQuestionConfigResponseValue*: CreateQuestionConfigResponse
  of CreateQuestionConfigResponse1Kind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[CreateQuestionConfigResponse1]): CreateQuestionConfigResponse1 =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return CreateQuestionConfigResponse1(kind: CreateQuestionConfigResponse1Kind.CreateQuestionConfigResponseVariant, CreateQuestionConfigResponseValue: to(node, CreateQuestionConfigResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as CreateQuestionConfigResponse: ", e.msg
  try:
    return CreateQuestionConfigResponse1(kind: CreateQuestionConfigResponse1Kind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of CreateQuestionConfigResponse1. JSON: " & $node)

