#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_block_success
import model_custom_config_parameters

# AnyOf type
type BlockFromCommentPublic200responseKind* {.pure.} = enum
  BlockSuccessVariant
  APIErrorVariant

type BlockFromCommentPublic200response* = object
  ## 
  case kind*: BlockFromCommentPublic200responseKind
  of BlockFromCommentPublic200responseKind.BlockSuccessVariant:
    BlockSuccessValue*: BlockSuccess
  of BlockFromCommentPublic200responseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[BlockFromCommentPublic200response]): BlockFromCommentPublic200response =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return BlockFromCommentPublic200response(kind: BlockFromCommentPublic200responseKind.BlockSuccessVariant, BlockSuccessValue: to(node, BlockSuccess))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as BlockSuccess: ", e.msg
  try:
    return BlockFromCommentPublic200response(kind: BlockFromCommentPublic200responseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of BlockFromCommentPublic200response. JSON: " & $node)

