#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_bulk_aggregate_question_results_response
import model_custom_config_parameters
import model_question_result_aggregation_overall

# AnyOf type
type BulkAggregateQuestionResults200responseKind* {.pure.} = enum
  BulkAggregateQuestionResultsResponseVariant
  APIErrorVariant

type BulkAggregateQuestionResults200response* = object
  ## 
  case kind*: BulkAggregateQuestionResults200responseKind
  of BulkAggregateQuestionResults200responseKind.BulkAggregateQuestionResultsResponseVariant:
    BulkAggregateQuestionResultsResponseValue*: BulkAggregateQuestionResultsResponse
  of BulkAggregateQuestionResults200responseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[BulkAggregateQuestionResults200response]): BulkAggregateQuestionResults200response =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return BulkAggregateQuestionResults200response(kind: BulkAggregateQuestionResults200responseKind.BulkAggregateQuestionResultsResponseVariant, BulkAggregateQuestionResultsResponseValue: to(node, BulkAggregateQuestionResultsResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as BulkAggregateQuestionResultsResponse: ", e.msg
  try:
    return BulkAggregateQuestionResults200response(kind: BulkAggregateQuestionResults200responseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of BulkAggregateQuestionResults200response. JSON: " & $node)
