#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type QuestionSubQuestionVisibility* {.pure.} = enum
  `0`
  `1`

func `%`*(v: QuestionSubQuestionVisibility): JsonNode =
  result = case v:
    of QuestionSubQuestionVisibility.`0`: %0
    of QuestionSubQuestionVisibility.`1`: %1

func `$`*(v: QuestionSubQuestionVisibility): string =
  result = case v:
    of QuestionSubQuestionVisibility.`0`: $(0)
    of QuestionSubQuestionVisibility.`1`: $(1)

proc to*(node: JsonNode, T: typedesc[QuestionSubQuestionVisibility]): QuestionSubQuestionVisibility =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum QuestionSubQuestionVisibility, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $(0):
    return QuestionSubQuestionVisibility.`0`
  of $(1):
    return QuestionSubQuestionVisibility.`1`
  else:
    raise newException(ValueError, "Invalid enum value for QuestionSubQuestionVisibility: " & strVal)
