#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type CommentQuestionsRequired* {.pure.} = enum
  `0`
  `1`

func `%`*(v: CommentQuestionsRequired): JsonNode =
  result = case v:
    of CommentQuestionsRequired.`0`: %0
    of CommentQuestionsRequired.`1`: %1

func `$`*(v: CommentQuestionsRequired): string =
  result = case v:
    of CommentQuestionsRequired.`0`: $(0)
    of CommentQuestionsRequired.`1`: $(1)

proc to*(node: JsonNode, T: typedesc[CommentQuestionsRequired]): CommentQuestionsRequired =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum CommentQuestionsRequired, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $(0):
    return CommentQuestionsRequired.`0`
  of $(1):
    return CommentQuestionsRequired.`1`
  else:
    raise newException(ValueError, "Invalid enum value for CommentQuestionsRequired: " & strVal)

