#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_search_users_response
import model_user_search_result

# AnyOf type
type SearchUsers200responseKind* {.pure.} = enum
  SearchUsersResponseVariant
  APIErrorVariant

type SearchUsers200response* = object
  ## 
  case kind*: SearchUsers200responseKind
  of SearchUsers200responseKind.SearchUsersResponseVariant:
    SearchUsersResponseValue*: SearchUsersResponse
  of SearchUsers200responseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[SearchUsers200response]): SearchUsers200response =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return SearchUsers200response(kind: SearchUsers200responseKind.SearchUsersResponseVariant, SearchUsersResponseValue: to(node, SearchUsersResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as SearchUsersResponse: ", e.msg
  try:
    return SearchUsers200response(kind: SearchUsers200responseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of SearchUsers200response. JSON: " & $node)
