#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables


type APIStatus* {.pure.} = enum
  Success
  Failed

func `%`*(v: APIStatus): JsonNode =
  result = case v:
    of APIStatus.Success: %"success"
    of APIStatus.Failed: %"failed"

func `$`*(v: APIStatus): string =
  result = case v:
    of APIStatus.Success: $("success")
    of APIStatus.Failed: $("failed")

