#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables


type CommentHTMLRenderingMode* {.pure.} = enum
  `0`
  `1`

func `%`*(v: CommentHTMLRenderingMode): JsonNode =
  result = case v:
    of CommentHTMLRenderingMode.`0`: %0
    of CommentHTMLRenderingMode.`1`: %1

func `$`*(v: CommentHTMLRenderingMode): string =
  result = case v:
    of CommentHTMLRenderingMode.`0`: $(0)
    of CommentHTMLRenderingMode.`1`: $(1)

