#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_gif_search_internal_error
import model_gif_search_response
import model_gif_search_response_images_inner_inner

# AnyOf type
type GetGifsSearchResponseKind* {.pure.} = enum
  GifSearchResponseVariant
  GifSearchInternalErrorVariant
  APIErrorVariant

type GetGifsSearchResponse* = object
  ## 
  case kind*: GetGifsSearchResponseKind
  of GetGifsSearchResponseKind.GifSearchResponseVariant:
    GifSearchResponseValue*: GifSearchResponse
  of GetGifsSearchResponseKind.GifSearchInternalErrorVariant:
    GifSearchInternalErrorValue*: GifSearchInternalError
  of GetGifsSearchResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetGifsSearchResponse]): GetGifsSearchResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetGifsSearchResponse(kind: GetGifsSearchResponseKind.GifSearchResponseVariant, GifSearchResponseValue: to(node, GifSearchResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GifSearchResponse: ", e.msg
  try:
    return GetGifsSearchResponse(kind: GetGifsSearchResponseKind.GifSearchInternalErrorVariant, GifSearchInternalErrorValue: to(node, GifSearchInternalError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GifSearchInternalError: ", e.msg
  try:
    return GetGifsSearchResponse(kind: GetGifsSearchResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetGifsSearchResponse. JSON: " & $node)

