#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type

type UpdateModeratorBody* = object
  ## 
  name*: Option[string]
  email*: Option[string]
  userId*: Option[string]
  moderationGroupIds*: Option[seq[string]]

