#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_create_tenant_user_response
import model_custom_config_parameters
import model_user

# AnyOf type
type CreateTenantUser200responseKind* {.pure.} = enum
  CreateTenantUserResponseVariant
  APIErrorVariant

type CreateTenantUser200response* = object
  ## 
  case kind*: CreateTenantUser200responseKind
  of CreateTenantUser200responseKind.CreateTenantUserResponseVariant:
    CreateTenantUserResponseValue*: CreateTenantUserResponse
  of CreateTenantUser200responseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[CreateTenantUser200response]): CreateTenantUser200response =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return CreateTenantUser200response(kind: CreateTenantUser200responseKind.CreateTenantUserResponseVariant, CreateTenantUserResponseValue: to(node, CreateTenantUserResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as CreateTenantUserResponse: ", e.msg
  try:
    return CreateTenantUser200response(kind: CreateTenantUser200responseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of CreateTenantUser200response. JSON: " & $node)

