#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_page_user_entry
import model_page_users_info_response

# AnyOf type
type GetUsersInfoResponseKind* {.pure.} = enum
  PageUsersInfoResponseVariant
  APIErrorVariant

type GetUsersInfoResponse* = object
  ## 
  case kind*: GetUsersInfoResponseKind
  of GetUsersInfoResponseKind.PageUsersInfoResponseVariant:
    PageUsersInfoResponseValue*: PageUsersInfoResponse
  of GetUsersInfoResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetUsersInfoResponse]): GetUsersInfoResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetUsersInfoResponse(kind: GetUsersInfoResponseKind.PageUsersInfoResponseVariant, PageUsersInfoResponseValue: to(node, PageUsersInfoResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as PageUsersInfoResponse: ", e.msg
  try:
    return GetUsersInfoResponse(kind: GetUsersInfoResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetUsersInfoResponse. JSON: " & $node)

