#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_api_tenant
import model_create_tenant_response
import model_custom_config_parameters

# AnyOf type
type CreateTenantResponse1Kind* {.pure.} = enum
  CreateTenantResponseVariant
  APIErrorVariant

type CreateTenantResponse1* = object
  ## 
  case kind*: CreateTenantResponse1Kind
  of CreateTenantResponse1Kind.CreateTenantResponseVariant:
    CreateTenantResponseValue*: CreateTenantResponse
  of CreateTenantResponse1Kind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[CreateTenantResponse1]): CreateTenantResponse1 =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return CreateTenantResponse1(kind: CreateTenantResponse1Kind.CreateTenantResponseVariant, CreateTenantResponseValue: to(node, CreateTenantResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as CreateTenantResponse: ", e.msg
  try:
    return CreateTenantResponse1(kind: CreateTenantResponse1Kind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of CreateTenantResponse1. JSON: " & $node)

