#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_query_predicate_value

type Operator* {.pure.} = enum
  Eq
  NotEq
  GreaterThan
  LessThan
  Contains

type QueryPredicate* = object
  ## 
  key*: string
  value*: QueryPredicate_value
  operator*: Operator

func `%`*(v: Operator): JsonNode =
  result = case v:
    of Operator.Eq: %"eq"
    of Operator.NotEq: %"not_eq"
    of Operator.GreaterThan: %"greater_than"
    of Operator.LessThan: %"less_than"
    of Operator.Contains: %"contains"
func `$`*(v: Operator): string =
  result = case v:
    of Operator.Eq: $("eq")
    of Operator.NotEq: $("not_eq")
    of Operator.GreaterThan: $("greater_than")
    of Operator.LessThan: $("less_than")
    of Operator.Contains: $("contains")

proc to*(node: JsonNode, T: typedesc[Operator]): Operator =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum Operator, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("eq"):
    return Operator.Eq
  of $("not_eq"):
    return Operator.NotEq
  of $("greater_than"):
    return Operator.GreaterThan
  of $("less_than"):
    return Operator.LessThan
  of $("contains"):
    return Operator.Contains
  else:
    raise newException(ValueError, "Invalid enum value for Operator: " & strVal)

