#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_create_feed_posts_response
import model_custom_config_parameters
import model_feed_post

# AnyOf type
type CreateFeedPostResponse1Kind* {.pure.} = enum
  CreateFeedPostsResponseVariant
  APIErrorVariant

type CreateFeedPostResponse1* = object
  ## 
  case kind*: CreateFeedPostResponse1Kind
  of CreateFeedPostResponse1Kind.CreateFeedPostsResponseVariant:
    CreateFeedPostsResponseValue*: CreateFeedPostsResponse
  of CreateFeedPostResponse1Kind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[CreateFeedPostResponse1]): CreateFeedPostResponse1 =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return CreateFeedPostResponse1(kind: CreateFeedPostResponse1Kind.CreateFeedPostsResponseVariant, CreateFeedPostsResponseValue: to(node, CreateFeedPostsResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as CreateFeedPostsResponse: ", e.msg
  try:
    return CreateFeedPostResponse1(kind: CreateFeedPostResponse1Kind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of CreateFeedPostResponse1. JSON: " & $node)

