#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_delete_comment_result
import model_remove_comment_action_response

# AnyOf type
type PostRemoveCommentResponseKind* {.pure.} = enum
  DeleteCommentResultVariant
  RemoveCommentActionResponseVariant

type PostRemoveCommentResponse* = object
  ## 
  case kind*: PostRemoveCommentResponseKind
  of PostRemoveCommentResponseKind.DeleteCommentResultVariant:
    DeleteCommentResultValue*: DeleteCommentResult
  of PostRemoveCommentResponseKind.RemoveCommentActionResponseVariant:
    RemoveCommentActionResponseValue*: RemoveCommentActionResponse

proc to*(node: JsonNode, T: typedesc[PostRemoveCommentResponse]): PostRemoveCommentResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return PostRemoveCommentResponse(kind: PostRemoveCommentResponseKind.DeleteCommentResultVariant, DeleteCommentResultValue: to(node, DeleteCommentResult))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as DeleteCommentResult: ", e.msg
  try:
    return PostRemoveCommentResponse(kind: PostRemoveCommentResponseKind.RemoveCommentActionResponseVariant, RemoveCommentActionResponseValue: to(node, RemoveCommentActionResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as RemoveCommentActionResponse: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of PostRemoveCommentResponse. JSON: " & $node)

