#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_create_user_badge_response
import model_api_error
import model_api_status
import model_custom_config_parameters
import model_user_badge

# AnyOf type
type CreateUserBadgeResponseKind* {.pure.} = enum
  APICreateUserBadgeResponseVariant
  APIErrorVariant

type CreateUserBadgeResponse* = object
  ## 
  case kind*: CreateUserBadgeResponseKind
  of CreateUserBadgeResponseKind.APICreateUserBadgeResponseVariant:
    APICreateUserBadgeResponseValue*: APICreateUserBadgeResponse
  of CreateUserBadgeResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[CreateUserBadgeResponse]): CreateUserBadgeResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return CreateUserBadgeResponse(kind: CreateUserBadgeResponseKind.APICreateUserBadgeResponseVariant, APICreateUserBadgeResponseValue: to(node, APICreateUserBadgeResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APICreateUserBadgeResponse: ", e.msg
  try:
    return CreateUserBadgeResponse(kind: CreateUserBadgeResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of CreateUserBadgeResponse. JSON: " & $node)

