#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_ignored_response
import model_user_notification_write_response

# AnyOf type
type UpdateUserNotificationStatus200responseKind* {.pure.} = enum
  UserNotificationWriteResponseVariant
  IgnoredResponseVariant
  APIErrorVariant

type UpdateUserNotificationStatus200response* = object
  ## 
  case kind*: UpdateUserNotificationStatus200responseKind
  of UpdateUserNotificationStatus200responseKind.UserNotificationWriteResponseVariant:
    UserNotificationWriteResponseValue*: UserNotificationWriteResponse
  of UpdateUserNotificationStatus200responseKind.IgnoredResponseVariant:
    IgnoredResponseValue*: IgnoredResponse
  of UpdateUserNotificationStatus200responseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[UpdateUserNotificationStatus200response]): UpdateUserNotificationStatus200response =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return UpdateUserNotificationStatus200response(kind: UpdateUserNotificationStatus200responseKind.UserNotificationWriteResponseVariant, UserNotificationWriteResponseValue: to(node, UserNotificationWriteResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as UserNotificationWriteResponse: ", e.msg
  try:
    return UpdateUserNotificationStatus200response(kind: UpdateUserNotificationStatus200responseKind.IgnoredResponseVariant, IgnoredResponseValue: to(node, IgnoredResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as IgnoredResponse: ", e.msg
  try:
    return UpdateUserNotificationStatus200response(kind: UpdateUserNotificationStatus200responseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of UpdateUserNotificationStatus200response. JSON: " & $node)
