#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_delete_comment_result
import model_remove_comment_action_response

# AnyOf type
type PostRemoveCommentApiResponseKind* {.pure.} = enum
  DeleteCommentResultVariant
  RemoveCommentActionResponseVariant

type PostRemoveCommentApiResponse* = object
  ## 
  case kind*: PostRemoveCommentApiResponseKind
  of PostRemoveCommentApiResponseKind.DeleteCommentResultVariant:
    DeleteCommentResultValue*: DeleteCommentResult
  of PostRemoveCommentApiResponseKind.RemoveCommentActionResponseVariant:
    RemoveCommentActionResponseValue*: RemoveCommentActionResponse

proc to*(node: JsonNode, T: typedesc[PostRemoveCommentApiResponse]): PostRemoveCommentApiResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return PostRemoveCommentApiResponse(kind: PostRemoveCommentApiResponseKind.DeleteCommentResultVariant, DeleteCommentResultValue: to(node, DeleteCommentResult))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as DeleteCommentResult: ", e.msg
  try:
    return PostRemoveCommentApiResponse(kind: PostRemoveCommentApiResponseKind.RemoveCommentActionResponseVariant, RemoveCommentActionResponseValue: to(node, RemoveCommentActionResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as RemoveCommentActionResponse: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of PostRemoveCommentApiResponse. JSON: " & $node)

