#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_public_api_get_comment_text_response

type GetCommentText200response* = object
  ## 
  status*: APIStatus
  commentText*: string
  sanitizedCommentText*: string
  reason*: string
  code*: string
  secondaryCode*: string
  bannedUntil*: int64
  maxCharacterLength*: int
  translatedError*: string
  customConfig*: CustomConfigParameters

