#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_f_comment_meta

type UpdatableCommentParams* = object
  ## 
  urlId*: Option[string]
  urlIdRaw*: Option[string]
  url*: Option[string]
  pageTitle*: Option[string]
  userId*: Option[string]
  commenterEmail*: Option[string]
  commenterName*: Option[string]
  commenterLink*: Option[string]
  comment*: Option[string]
  commentHTML*: Option[string]
  parentId*: Option[string]
  date*: Option[float64]
  localDateString*: Option[string]
  localDateHours*: Option[int]
  votes*: Option[int]
  votesUp*: Option[int]
  votesDown*: Option[int]
  expireAt*: Option[string]
  verified*: Option[bool]
  verifiedDate*: Option[string]
  notificationSentForParent*: Option[bool]
  notificationSentForParentTenant*: Option[bool]
  reviewed*: Option[bool]
  externalId*: Option[string]
  externalParentId*: Option[string]
  avatarSrc*: Option[string]
  isSpam*: Option[bool]
  approved*: Option[bool]
  isDeleted*: Option[bool]
  isDeletedUser*: Option[bool]
  isByAdmin*: Option[bool]
  isByModerator*: Option[bool]
  isPinned*: Option[bool]
  isLocked*: Option[bool]
  flagCount*: Option[int]
  displayLabel*: Option[string]
  meta*: Option[FComment_meta]
  moderationGroupIds*: Option[seq[string]]
  feedbackIds*: Option[seq[string]]

