#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_any_type
import model_api_status
import model_public_comment
import model_user_session_info

type SaveCommentResponseOptimized* = object
  ## 
  status*: APIStatus
  comment*: PublicComment
  user*: UserSessionInfo
  moduleData*: Table[string, JsonNode] ## Construct a type with a set of properties K of type T

