#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_notification_object_type
import model_notification_type

type UserNotification* = object
  ## 
  id*: string
  tenantId*: string
  userId*: string
  anonUserId*: string
  urlId*: string
  url*: string
  pageTitle*: string
  relatedObjectType*: NotificationObjectType
  relatedObjectId*: string
  viewed*: bool
  isUnreadMessage*: bool
  sent*: bool
  createdAt*: string
  `type`*: NotificationType
  fromCommentId*: string
  fromVoteId*: string
  fromUserName*: string
  fromUserId*: string
  fromUserAvatarSrc*: string
  optedOut*: bool
  count*: int64
  relatedIds*: seq[string]
  fromUserIds*: seq[string]
  fromUserNames*: seq[string]

