#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_tenant_hash_tag

type CreateHashTagResponse* = object
  ## 
  status*: APIStatus
  hashTag*: TenantHashTag


# Custom JSON deserialization for CreateHashTagResponse with custom field names
proc to*(node: JsonNode, T: typedesc[CreateHashTagResponse]): CreateHashTagResponse =
  result = CreateHashTagResponse()
  if node.kind == JObject:
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)
    if node.hasKey("hashTag"):
      result.hashTag = to(node["hashTag"], TenantHashTag)

# Custom JSON serialization for CreateHashTagResponse with custom field names
proc `%`*(obj: CreateHashTagResponse): JsonNode =
  result = newJObject()
  result["status"] = %obj.status
  result["hashTag"] = %obj.hashTag

