#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_comment_user_badge_info

type PublicComment* = object
  ## 
  id*: string
  userId*: string
  commenterName*: string
  commenterLink*: string
  commentHTML*: string
  parentId*: string
  date*: string
  votes*: int
  votesUp*: int
  votesDown*: int
  verified*: bool
  avatarSrc*: string
  hasImages*: bool
  isByAdmin*: bool
  isByModerator*: bool
  isPinned*: bool
  isLocked*: bool
  displayLabel*: string
  rating*: float64
  badges*: seq[CommentUserBadgeInfo]
  viewCount*: int64
  isDeleted*: bool
  isDeletedUser*: bool
  isSpam*: bool
  anonUserId*: string
  feedbackIds*: seq[string]
  requiresVerification*: bool
  editKey*: string
  isUnread*: bool
  myVoteId*: string
  isVotedDown*: bool
  isVotedUp*: bool
  hasChildren*: bool ## This is always set when asTree=true
  nestedChildrenCount*: int ## The total nested child count included in this response (may be more available w/ pagination) Only set with asTree=true, otherwise this will be null.
  childCount*: int ## You must ask the API to count children (with asTree=true&countChildren=true), otherwise this will be null. This will be the complete direct child count, whereas children may only contain a subset based on pagination.
  children*: seq[PublicComment]
  isFlagged*: bool
  isBlocked*: bool

