#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_get_moderator_response
import model_moderator

# AnyOf type
type GetModeratorResponse1Kind* {.pure.} = enum
  GetModeratorResponseVariant
  APIErrorVariant

type GetModeratorResponse1* = object
  ## 
  case kind*: GetModeratorResponse1Kind
  of GetModeratorResponse1Kind.GetModeratorResponseVariant:
    GetModeratorResponseValue*: GetModeratorResponse
  of GetModeratorResponse1Kind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetModeratorResponse1]): GetModeratorResponse1 =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetModeratorResponse1(kind: GetModeratorResponse1Kind.GetModeratorResponseVariant, GetModeratorResponseValue: to(node, GetModeratorResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetModeratorResponse: ", e.msg
  try:
    return GetModeratorResponse1(kind: GetModeratorResponse1Kind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetModeratorResponse1. JSON: " & $node)

