#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_add_domain_config_response_any_of
import model_any_type
import model_get_domain_configs_response_any_of1

# AnyOf type
type PatchDomainConfigResponseKind* {.pure.} = enum
  AddDomainConfigResponseAnyOfVariant
  GetDomainConfigsResponseAnyOf1Variant

type PatchDomainConfigResponse* = object
  ## 
  case kind*: PatchDomainConfigResponseKind
  of PatchDomainConfigResponseKind.AddDomainConfigResponseAnyOfVariant:
    AddDomainConfigResponse_anyOfValue*: AddDomainConfigResponseAnyOf
  of PatchDomainConfigResponseKind.GetDomainConfigsResponseAnyOf1Variant:
    GetDomainConfigsResponse_anyOf_1Value*: GetDomainConfigsResponseAnyOf1

proc to*(node: JsonNode, T: typedesc[PatchDomainConfigResponse]): PatchDomainConfigResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return PatchDomainConfigResponse(kind: PatchDomainConfigResponseKind.AddDomainConfigResponseAnyOfVariant, AddDomainConfigResponse_anyOfValue: to(node, AddDomainConfigResponseAnyOf))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as AddDomainConfigResponseAnyOf: ", e.msg
  try:
    return PatchDomainConfigResponse(kind: PatchDomainConfigResponseKind.GetDomainConfigsResponseAnyOf1Variant, GetDomainConfigsResponse_anyOf_1Value: to(node, GetDomainConfigsResponseAnyOf1))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetDomainConfigsResponseAnyOf1: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of PatchDomainConfigResponse. JSON: " & $node)

