#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ModerationFilter* = object
  ## 
  reviewed*: Option[bool]
  approved*: Option[bool]
  isSpam*: Option[bool]
  isBannedUser*: Option[bool]
  isLocked*: Option[bool]
  flagCountGt*: Option[float64]
  userId*: Option[string]
  urlId*: Option[string]
  domain*: Option[string]
  moderationGroupIds*: Option[seq[string]]
  commentTextSearch*: Option[seq[string]] ## Text search terms. Each term is matched case-insensitively against the comment text. A term wrapped in quotes means exact phrase match.
  exactCommentText*: Option[string] ## Set by the `exact=\"...\"` search syntax. The comment text must equal this value exactly (case-sensitive, full-string), as opposed to the substring matching of commentTextSearch.


# Custom JSON deserialization for ModerationFilter with custom field names
proc to*(node: JsonNode, T: typedesc[ModerationFilter]): ModerationFilter =
  result = ModerationFilter()
  if node.kind == JObject:
    if node.hasKey("reviewed") and node["reviewed"].kind != JNull:
      result.reviewed = some(to(node["reviewed"], typeof(result.reviewed.get())))
    if node.hasKey("approved") and node["approved"].kind != JNull:
      result.approved = some(to(node["approved"], typeof(result.approved.get())))
    if node.hasKey("isSpam") and node["isSpam"].kind != JNull:
      result.isSpam = some(to(node["isSpam"], typeof(result.isSpam.get())))
    if node.hasKey("isBannedUser") and node["isBannedUser"].kind != JNull:
      result.isBannedUser = some(to(node["isBannedUser"], typeof(result.isBannedUser.get())))
    if node.hasKey("isLocked") and node["isLocked"].kind != JNull:
      result.isLocked = some(to(node["isLocked"], typeof(result.isLocked.get())))
    if node.hasKey("flagCountGt") and node["flagCountGt"].kind != JNull:
      result.flagCountGt = some(to(node["flagCountGt"], typeof(result.flagCountGt.get())))
    if node.hasKey("userId") and node["userId"].kind != JNull:
      result.userId = some(to(node["userId"], typeof(result.userId.get())))
    if node.hasKey("urlId") and node["urlId"].kind != JNull:
      result.urlId = some(to(node["urlId"], typeof(result.urlId.get())))
    if node.hasKey("domain") and node["domain"].kind != JNull:
      result.domain = some(to(node["domain"], typeof(result.domain.get())))
    if node.hasKey("moderationGroupIds") and node["moderationGroupIds"].kind != JNull:
      result.moderationGroupIds = some(to(node["moderationGroupIds"], typeof(result.moderationGroupIds.get())))
    if node.hasKey("commentTextSearch") and node["commentTextSearch"].kind != JNull:
      result.commentTextSearch = some(to(node["commentTextSearch"], typeof(result.commentTextSearch.get())))
    if node.hasKey("exactCommentText") and node["exactCommentText"].kind != JNull:
      result.exactCommentText = some(to(node["exactCommentText"], typeof(result.exactCommentText.get())))

# Custom JSON serialization for ModerationFilter with custom field names
proc `%`*(obj: ModerationFilter): JsonNode =
  result = newJObject()
  if obj.reviewed.isSome():
    result["reviewed"] = %obj.reviewed.get()
  if obj.approved.isSome():
    result["approved"] = %obj.approved.get()
  if obj.isSpam.isSome():
    result["isSpam"] = %obj.isSpam.get()
  if obj.isBannedUser.isSome():
    result["isBannedUser"] = %obj.isBannedUser.get()
  if obj.isLocked.isSome():
    result["isLocked"] = %obj.isLocked.get()
  if obj.flagCountGt.isSome():
    result["flagCountGt"] = %obj.flagCountGt.get()
  if obj.userId.isSome():
    result["userId"] = %obj.userId.get()
  if obj.urlId.isSome():
    result["urlId"] = %obj.urlId.get()
  if obj.domain.isSome():
    result["domain"] = %obj.domain.get()
  if obj.moderationGroupIds.isSome():
    result["moderationGroupIds"] = %obj.moderationGroupIds.get()
  if obj.commentTextSearch.isSome():
    result["commentTextSearch"] = %obj.commentTextSearch.get()
  if obj.exactCommentText.isSome():
    result["exactCommentText"] = %obj.exactCommentText.get()

