#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_custom_email_template

type GetEmailTemplateResponse* = object
  ## 
  status*: APIStatus
  emailTemplate*: CustomEmailTemplate


# Custom JSON deserialization for GetEmailTemplateResponse with custom field names
proc to*(node: JsonNode, T: typedesc[GetEmailTemplateResponse]): GetEmailTemplateResponse =
  result = GetEmailTemplateResponse()
  if node.kind == JObject:
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)
    if node.hasKey("emailTemplate"):
      result.emailTemplate = to(node["emailTemplate"], CustomEmailTemplate)

# Custom JSON serialization for GetEmailTemplateResponse with custom field names
proc `%`*(obj: GetEmailTemplateResponse): JsonNode =
  result = newJObject()
  result["status"] = %obj.status
  result["emailTemplate"] = %obj.emailTemplate

