#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_get_comments_response_with_presence_public_comment
import model_object
import model_public_comment
import model_user_session_info

# AnyOf type
type GetCommentsPublicResponseKind* {.pure.} = enum
  GetCommentsResponseWithPresencePublicCommentVariant
  APIErrorVariant

type GetCommentsPublicResponse* = object
  ## 
  case kind*: GetCommentsPublicResponseKind
  of GetCommentsPublicResponseKind.GetCommentsResponseWithPresencePublicCommentVariant:
    GetCommentsResponseWithPresence_PublicComment_Value*: GetCommentsResponseWithPresencePublicComment
  of GetCommentsPublicResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetCommentsPublicResponse]): GetCommentsPublicResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetCommentsPublicResponse(kind: GetCommentsPublicResponseKind.GetCommentsResponseWithPresencePublicCommentVariant, GetCommentsResponseWithPresence_PublicComment_Value: to(node, GetCommentsResponseWithPresencePublicComment))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetCommentsResponseWithPresencePublicComment: ", e.msg
  try:
    return GetCommentsPublicResponse(kind: GetCommentsPublicResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetCommentsPublicResponse. JSON: " & $node)

