#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_create_moderator_response
import model_custom_config_parameters
import model_moderator

# AnyOf type
type CreateModerator200responseKind* {.pure.} = enum
  CreateModeratorResponseVariant
  APIErrorVariant

type CreateModerator200response* = object
  ## 
  case kind*: CreateModerator200responseKind
  of CreateModerator200responseKind.CreateModeratorResponseVariant:
    CreateModeratorResponseValue*: CreateModeratorResponse
  of CreateModerator200responseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[CreateModerator200response]): CreateModerator200response =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return CreateModerator200response(kind: CreateModerator200responseKind.CreateModeratorResponseVariant, CreateModeratorResponseValue: to(node, CreateModeratorResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as CreateModeratorResponse: ", e.msg
  try:
    return CreateModerator200response(kind: CreateModerator200responseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of CreateModerator200response. JSON: " & $node)

