#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type VoteResponseUser* = object
  ## 
  sessionId*: Option[string]


# Custom JSON deserialization for VoteResponseUser with custom field names
proc to*(node: JsonNode, T: typedesc[VoteResponseUser]): VoteResponseUser =
  result = VoteResponseUser()
  if node.kind == JObject:
    if node.hasKey("sessionId") and node["sessionId"].kind != JNull:
      result.sessionId = some(to(node["sessionId"], typeof(result.sessionId.get())))

# Custom JSON serialization for VoteResponseUser with custom field names
proc `%`*(obj: VoteResponseUser): JsonNode =
  result = newJObject()
  if obj.sessionId.isSome():
    result["sessionId"] = %obj.sessionId.get()
