#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_get_hash_tags_response
import model_tenant_hash_tag

# AnyOf type
type GetHashTagsResponse1Kind* {.pure.} = enum
  GetHashTagsResponseVariant
  APIErrorVariant

type GetHashTagsResponse1* = object
  ## 
  case kind*: GetHashTagsResponse1Kind
  of GetHashTagsResponse1Kind.GetHashTagsResponseVariant:
    GetHashTagsResponseValue*: GetHashTagsResponse
  of GetHashTagsResponse1Kind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetHashTagsResponse1]): GetHashTagsResponse1 =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetHashTagsResponse1(kind: GetHashTagsResponse1Kind.GetHashTagsResponseVariant, GetHashTagsResponseValue: to(node, GetHashTagsResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetHashTagsResponse: ", e.msg
  try:
    return GetHashTagsResponse1(kind: GetHashTagsResponse1Kind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetHashTagsResponse1. JSON: " & $node)

