#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_get_user_internal_profile_response
import model_get_user_internal_profile_response_profile

# AnyOf type
type GetUserInternalProfileResponse1Kind* {.pure.} = enum
  GetUserInternalProfileResponseVariant
  APIErrorVariant

type GetUserInternalProfileResponse1* = object
  ## 
  case kind*: GetUserInternalProfileResponse1Kind
  of GetUserInternalProfileResponse1Kind.GetUserInternalProfileResponseVariant:
    GetUserInternalProfileResponseValue*: GetUserInternalProfileResponse
  of GetUserInternalProfileResponse1Kind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetUserInternalProfileResponse1]): GetUserInternalProfileResponse1 =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetUserInternalProfileResponse1(kind: GetUserInternalProfileResponse1Kind.GetUserInternalProfileResponseVariant, GetUserInternalProfileResponseValue: to(node, GetUserInternalProfileResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetUserInternalProfileResponse: ", e.msg
  try:
    return GetUserInternalProfileResponse1(kind: GetUserInternalProfileResponse1Kind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetUserInternalProfileResponse1. JSON: " & $node)

