#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_moderation_page_search_projected
import model_moderation_page_search_response

# AnyOf type
type GetSearchPagesResponseKind* {.pure.} = enum
  ModerationPageSearchResponseVariant
  APIErrorVariant

type GetSearchPagesResponse* = object
  ## 
  case kind*: GetSearchPagesResponseKind
  of GetSearchPagesResponseKind.ModerationPageSearchResponseVariant:
    ModerationPageSearchResponseValue*: ModerationPageSearchResponse
  of GetSearchPagesResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetSearchPagesResponse]): GetSearchPagesResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetSearchPagesResponse(kind: GetSearchPagesResponseKind.ModerationPageSearchResponseVariant, ModerationPageSearchResponseValue: to(node, ModerationPageSearchResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as ModerationPageSearchResponse: ", e.msg
  try:
    return GetSearchPagesResponse(kind: GetSearchPagesResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetSearchPagesResponse. JSON: " & $node)

