#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_feed_post_media_item_asset

type FeedPostMediaItem* = object
  ## 
  title*: string
  linkUrl*: string
  sizes*: seq[FeedPostMediaItemAsset]

