#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type NotificationObjectType* {.pure.} = enum
  `0`
  `1`
  `2`

func `%`*(v: NotificationObjectType): JsonNode =
  result = case v:
    of NotificationObjectType.`0`: %0
    of NotificationObjectType.`1`: %1
    of NotificationObjectType.`2`: %2

func `$`*(v: NotificationObjectType): string =
  result = case v:
    of NotificationObjectType.`0`: $(0)
    of NotificationObjectType.`1`: $(1)
    of NotificationObjectType.`2`: $(2)

proc to*(node: JsonNode, T: typedesc[NotificationObjectType]): NotificationObjectType =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum NotificationObjectType, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $(0):
    return NotificationObjectType.`0`
  of $(1):
    return NotificationObjectType.`1`
  of $(2):
    return NotificationObjectType.`2`
  else:
    raise newException(ValueError, "Invalid enum value for NotificationObjectType: " & strVal)

