#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status
import model_moderation_page_search_projected

type ModerationPageSearchResponse* = object
  ## 
  pages*: seq[ModerationPageSearchProjected]
  status*: APIStatus


# Custom JSON deserialization for ModerationPageSearchResponse with custom field names
proc to*(node: JsonNode, T: typedesc[ModerationPageSearchResponse]): ModerationPageSearchResponse =
  result = ModerationPageSearchResponse()
  if node.kind == JObject:
    if node.hasKey("pages"):
      result.pages = to(node["pages"], seq[ModerationPageSearchProjected])
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)

# Custom JSON serialization for ModerationPageSearchResponse with custom field names
proc `%`*(obj: ModerationPageSearchResponse): JsonNode =
  result = newJObject()
  result["pages"] = %obj.pages
  result["status"] = %obj.status

