#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_api_ticket_detail
import model_custom_config_parameters
import model_get_ticket_response

# AnyOf type
type GetTicketResponse1Kind* {.pure.} = enum
  GetTicketResponseVariant
  APIErrorVariant

type GetTicketResponse1* = object
  ## 
  case kind*: GetTicketResponse1Kind
  of GetTicketResponse1Kind.GetTicketResponseVariant:
    GetTicketResponseValue*: GetTicketResponse
  of GetTicketResponse1Kind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetTicketResponse1]): GetTicketResponse1 =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetTicketResponse1(kind: GetTicketResponse1Kind.GetTicketResponseVariant, GetTicketResponseValue: to(node, GetTicketResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetTicketResponse: ", e.msg
  try:
    return GetTicketResponse1(kind: GetTicketResponse1Kind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetTicketResponse1. JSON: " & $node)

