#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_api_audit_log
import model_api_status

type GetAuditLogsResponse* = object
  ## 
  status*: APIStatus
  auditLogs*: seq[APIAuditLog]

