#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_event_log_entry
import model_get_event_log_response

type GetEventLog200response* = object
  ## 
  events*: seq[EventLogEntry]
  status*: APIStatus
  reason*: string
  code*: string
  secondaryCode*: string
  bannedUntil*: int64
  maxCharacterLength*: int
  translatedError*: string
  customConfig*: CustomConfigParameters

