#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_email_template_definition
import model_get_email_template_definitions_response

# AnyOf type
type GetEmailTemplateDefinitions200responseKind* {.pure.} = enum
  GetEmailTemplateDefinitionsResponseVariant
  APIErrorVariant

type GetEmailTemplateDefinitions200response* = object
  ## 
  case kind*: GetEmailTemplateDefinitions200responseKind
  of GetEmailTemplateDefinitions200responseKind.GetEmailTemplateDefinitionsResponseVariant:
    GetEmailTemplateDefinitionsResponseValue*: GetEmailTemplateDefinitionsResponse
  of GetEmailTemplateDefinitions200responseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetEmailTemplateDefinitions200response]): GetEmailTemplateDefinitions200response =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetEmailTemplateDefinitions200response(kind: GetEmailTemplateDefinitions200responseKind.GetEmailTemplateDefinitionsResponseVariant, GetEmailTemplateDefinitionsResponseValue: to(node, GetEmailTemplateDefinitionsResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetEmailTemplateDefinitionsResponse: ", e.msg
  try:
    return GetEmailTemplateDefinitions200response(kind: GetEmailTemplateDefinitions200responseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetEmailTemplateDefinitions200response. JSON: " & $node)

