#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_empty_response
import model_api_error
import model_api_status
import model_custom_config_parameters

# AnyOf type
type UnLockCommentResponseKind* {.pure.} = enum
  APIErrorVariant
  APIEmptyResponseVariant

type UnLockCommentResponse* = object
  ## 
  case kind*: UnLockCommentResponseKind
  of UnLockCommentResponseKind.APIErrorVariant:
    APIErrorValue*: APIError
  of UnLockCommentResponseKind.APIEmptyResponseVariant:
    APIEmptyResponseValue*: APIEmptyResponse

proc to*(node: JsonNode, T: typedesc[UnLockCommentResponse]): UnLockCommentResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return UnLockCommentResponse(kind: UnLockCommentResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  try:
    return UnLockCommentResponse(kind: UnLockCommentResponseKind.APIEmptyResponseVariant, APIEmptyResponseValue: to(node, APIEmptyResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIEmptyResponse: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of UnLockCommentResponse. JSON: " & $node)

