#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_aggregation_operation
import model_aggregation_request_sort
import model_query_predicate

type AggregationRequest* = object
  ## The aggregation request accepts a resource, optional grouping keys, an array of operations, and an optional sort
  query*: Option[seq[QueryPredicate]]
  resourceName*: string
  groupBy*: Option[seq[string]]
  operations*: seq[AggregationOperation]
  sort*: Option[AggregationRequest_sort]

