#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type CommentHTMLRenderingMode* {.pure.} = enum
  `0`
  `1`

func `%`*(v: CommentHTMLRenderingMode): JsonNode =
  result = case v:
    of CommentHTMLRenderingMode.`0`: %0
    of CommentHTMLRenderingMode.`1`: %1

func `$`*(v: CommentHTMLRenderingMode): string =
  result = case v:
    of CommentHTMLRenderingMode.`0`: $(0)
    of CommentHTMLRenderingMode.`1`: $(1)

proc to*(node: JsonNode, T: typedesc[CommentHTMLRenderingMode]): CommentHTMLRenderingMode =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum CommentHTMLRenderingMode, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $(0):
    return CommentHTMLRenderingMode.`0`
  of $(1):
    return CommentHTMLRenderingMode.`1`
  else:
    raise newException(ValueError, "Invalid enum value for CommentHTMLRenderingMode: " & strVal)
