#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status

type ModerationAPIGetCommentIdsResponse* = object
  ## 
  ids*: seq[string]
  hasMore*: bool
  status*: APIStatus


# Custom JSON deserialization for ModerationAPIGetCommentIdsResponse with custom field names
proc to*(node: JsonNode, T: typedesc[ModerationAPIGetCommentIdsResponse]): ModerationAPIGetCommentIdsResponse =
  result = ModerationAPIGetCommentIdsResponse()
  if node.kind == JObject:
    if node.hasKey("ids"):
      result.ids = to(node["ids"], seq[string])
    if node.hasKey("hasMore"):
      result.hasMore = to(node["hasMore"], bool)
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)

# Custom JSON serialization for ModerationAPIGetCommentIdsResponse with custom field names
proc `%`*(obj: ModerationAPIGetCommentIdsResponse): JsonNode =
  result = newJObject()
  result["ids"] = %obj.ids
  result["hasMore"] = %obj.hasMore
  result["status"] = %obj.status

