#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status

type GetV2PageReacts* = object
  ## 
  reactedIds*: Option[seq[string]]
  counts*: Option[Table[string, float64]] ## Construct a type with a set of properties K of type T
  status*: APIStatus

