#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_get_moderator_response
import model_moderator

# AnyOf type
type GetModerator200responseKind* {.pure.} = enum
  GetModeratorResponseVariant
  APIErrorVariant

type GetModerator200response* = object
  ## 
  case kind*: GetModerator200responseKind
  of GetModerator200responseKind.GetModeratorResponseVariant:
    GetModeratorResponseValue*: GetModeratorResponse
  of GetModerator200responseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetModerator200response]): GetModerator200response =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetModerator200response(kind: GetModerator200responseKind.GetModeratorResponseVariant, GetModeratorResponseValue: to(node, GetModeratorResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetModeratorResponse: ", e.msg
  try:
    return GetModerator200response(kind: GetModerator200responseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetModerator200response. JSON: " & $node)

