#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_comment_user_badge_info

type UserSessionInfo* = object
  ## 
  id*: string
  authorized*: bool
  avatarSrc*: string
  badges*: seq[CommentUserBadgeInfo]
  displayLabel*: string
  displayName*: string
  email*: string
  groupIds*: seq[string]
  hasBlockedUsers*: bool
  isAnonSession*: bool
  sessionId*: string
  username*: string
  websiteUrl*: string

