#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type ReplaceTenantUserBody* = object
  ## 
  username*: string
  email*: string
  displayName*: Option[string]
  websiteUrl*: Option[string]
  signUpDate*: Option[float64]
  locale*: Option[string]
  verified*: Option[bool]
  loginCount*: Option[float64]
  optedInNotifications*: Option[bool]
  optedInTenantNotifications*: Option[bool]
  hideAccountCode*: Option[bool]
  avatarSrc*: Option[string]
  isHelpRequestAdmin*: Option[bool]
  isAccountOwner*: Option[bool]
  isAdminAdmin*: Option[bool]
  isBillingAdmin*: Option[bool]
  isAnalyticsAdmin*: Option[bool]
  isCustomizationAdmin*: Option[bool]
  isManageDataAdmin*: Option[bool]
  isCommentModeratorAdmin*: Option[bool]
  isAPIAdmin*: Option[bool]
  moderatorIds*: Option[seq[string]]
  digestEmailFrequency*: Option[float64]
  displayLabel*: Option[string]
  createdFromUrlId*: Option[string]
  createdFromTenantId*: Option[string]
  lastLoginDate*: Option[float64]
  karma*: Option[float64]

