#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables


type AggregateTimeBucket* {.pure.} = enum
  Day
  Month
  Year

func `%`*(v: AggregateTimeBucket): JsonNode =
  result = case v:
    of AggregateTimeBucket.Day: %"day"
    of AggregateTimeBucket.Month: %"month"
    of AggregateTimeBucket.Year: %"year"

func `$`*(v: AggregateTimeBucket): string =
  result = case v:
    of AggregateTimeBucket.Day: $("day")
    of AggregateTimeBucket.Month: $("month")
    of AggregateTimeBucket.Year: $("year")

