#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type VoteDir* {.pure.} = enum
  Up
  Down

type VoteBodyParams* = object
  ## 
  commenterEmail*: Option[string]
  commenterName*: Option[string]
  voteDir*: VoteDir
  url*: Option[string]

func `%`*(v: VoteDir): JsonNode =
  result = case v:
    of VoteDir.Up: %"up"
    of VoteDir.Down: %"down"

func `$`*(v: VoteDir): string =
  result = case v:
    of VoteDir.Up: $("up")
    of VoteDir.Down: $("down")

proc to*(node: JsonNode, T: typedesc[VoteDir]): VoteDir =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum VoteDir, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("up"):
    return VoteDir.Up
  of $("down"):
    return VoteDir.Down
  else:
    raise newException(ValueError, "Invalid enum value for VoteDir: " & strVal)
