#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_any_type
import model_get_domain_configs_response_any_of
import model_get_domain_configs_response_any_of1

# AnyOf type
type GetDomainConfigsResponseKind* {.pure.} = enum
  GetDomainConfigsResponseAnyOfVariant
  GetDomainConfigsResponseAnyOf1Variant

type GetDomainConfigsResponse* = object
  ## 
  case kind*: GetDomainConfigsResponseKind
  of GetDomainConfigsResponseKind.GetDomainConfigsResponseAnyOfVariant:
    GetDomainConfigsResponse_anyOfValue*: GetDomainConfigsResponseAnyOf
  of GetDomainConfigsResponseKind.GetDomainConfigsResponseAnyOf1Variant:
    GetDomainConfigsResponse_anyOf_1Value*: GetDomainConfigsResponseAnyOf1

proc to*(node: JsonNode, T: typedesc[GetDomainConfigsResponse]): GetDomainConfigsResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetDomainConfigsResponse(kind: GetDomainConfigsResponseKind.GetDomainConfigsResponseAnyOfVariant, GetDomainConfigsResponse_anyOfValue: to(node, GetDomainConfigsResponseAnyOf))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetDomainConfigsResponseAnyOf: ", e.msg
  try:
    return GetDomainConfigsResponse(kind: GetDomainConfigsResponseKind.GetDomainConfigsResponseAnyOf1Variant, GetDomainConfigsResponse_anyOf_1Value: to(node, GetDomainConfigsResponseAnyOf1))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetDomainConfigsResponseAnyOf1: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetDomainConfigsResponse. JSON: " & $node)

