#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_create_tenant_package_response
import model_custom_config_parameters
import model_tenant_package

# AnyOf type
type CreateTenantPackage200responseKind* {.pure.} = enum
  CreateTenantPackageResponseVariant
  APIErrorVariant

type CreateTenantPackage200response* = object
  ## 
  case kind*: CreateTenantPackage200responseKind
  of CreateTenantPackage200responseKind.CreateTenantPackageResponseVariant:
    CreateTenantPackageResponseValue*: CreateTenantPackageResponse
  of CreateTenantPackage200responseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[CreateTenantPackage200response]): CreateTenantPackage200response =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return CreateTenantPackage200response(kind: CreateTenantPackage200responseKind.CreateTenantPackageResponseVariant, CreateTenantPackageResponseValue: to(node, CreateTenantPackageResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as CreateTenantPackageResponse: ", e.msg
  try:
    return CreateTenantPackage200response(kind: CreateTenantPackage200responseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of CreateTenantPackage200response. JSON: " & $node)

