#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_get_user_badge_response
import model_api_status
import model_custom_config_parameters
import model_user_badge

# AnyOf type
type GetUserBadgeResponseKind* {.pure.} = enum
  APIGetUserBadgeResponseVariant
  APIErrorVariant

type GetUserBadgeResponse* = object
  ## 
  case kind*: GetUserBadgeResponseKind
  of GetUserBadgeResponseKind.APIGetUserBadgeResponseVariant:
    APIGetUserBadgeResponseValue*: APIGetUserBadgeResponse
  of GetUserBadgeResponseKind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetUserBadgeResponse]): GetUserBadgeResponse =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetUserBadgeResponse(kind: GetUserBadgeResponseKind.APIGetUserBadgeResponseVariant, APIGetUserBadgeResponseValue: to(node, APIGetUserBadgeResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIGetUserBadgeResponse: ", e.msg
  try:
    return GetUserBadgeResponse(kind: GetUserBadgeResponseKind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetUserBadgeResponse. JSON: " & $node)

