#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables


type APISSOUser* = object
  ## 
  id*: string
  username*: string
  websiteUrl*: string
  email*: string
  signUpDate*: int64
  createdFromUrlId*: string
  loginCount*: int
  avatarSrc*: string
  optedInNotifications*: bool
  optedInSubscriptionNotifications*: bool
  displayLabel*: string
  displayName*: string
  isAccountOwner*: bool
  isAdminAdmin*: bool
  isCommentModeratorAdmin*: bool
  isProfileActivityPrivate*: bool
  isProfileCommentsPrivate*: bool
  isProfileDMDisabled*: bool
  hasBlockedUsers*: bool
  groupIds*: seq[string]

