#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_status

type DeleteFeedPostPublicResponseAnyOf* = object
  ## 
  status*: APIStatus


# Custom JSON deserialization for DeleteFeedPostPublicResponseAnyOf with custom field names
proc to*(node: JsonNode, T: typedesc[DeleteFeedPostPublicResponseAnyOf]): DeleteFeedPostPublicResponseAnyOf =
  result = DeleteFeedPostPublicResponseAnyOf()
  if node.kind == JObject:
    if node.hasKey("status"):
      result.status = to(node["status"], APIStatus)

# Custom JSON serialization for DeleteFeedPostPublicResponseAnyOf with custom field names
proc `%`*(obj: DeleteFeedPostPublicResponseAnyOf): JsonNode =
  result = newJObject()
  result["status"] = %obj.status

