#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options


type `Type`* {.pure.} = enum
  User
  Sso

type CommentUserMentionInfo* = object
  ## 
  id*: string
  tag*: string
  rawTag*: Option[string]
  `type`*: Option[`Type`]
  sent*: Option[bool]

func `%`*(v: `Type`): JsonNode =
  result = case v:
    of `Type`.User: %"user"
    of `Type`.Sso: %"sso"
func `$`*(v: `Type`): string =
  result = case v:
    of `Type`.User: $("user")
    of `Type`.Sso: $("sso")

proc to*(node: JsonNode, T: typedesc[`Type`]): `Type` =
  if node.kind != JString:
    raise newException(ValueError, "Expected string for enum `Type`, got " & $node.kind)
  let strVal = node.getStr()
  case strVal:
  of $("user"):
    return `Type`.User
  of $("sso"):
    return `Type`.Sso
  else:
    raise newException(ValueError, "Invalid enum value for `Type`: " & strVal)

