#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables

import model_comment_user_badge_info

type PubSubComment* = object
  ## 
  id*: string
  tenantId*: string
  userId*: string
  urlId*: string
  commenterName*: string
  commenterLink*: string
  commentHTML*: string
  comment*: string
  parentId*: string
  votes*: int
  votesUp*: int
  votesDown*: int
  verified*: bool
  avatarSrc*: string
  hasImages*: bool
  hasLinks*: bool
  isByAdmin*: bool
  isByModerator*: bool
  isPinned*: bool
  isLocked*: bool
  displayLabel*: string
  rating*: float64
  badges*: seq[CommentUserBadgeInfo]
  viewCount*: int64
  isDeleted*: bool
  isDeletedUser*: bool
  isSpam*: bool
  anonUserId*: string
  feedbackIds*: seq[string]
  flagCount*: int
  domain*: string
  url*: string
  pageTitle*: string
  expireAt*: string
  reviewed*: bool
  hasCode*: bool
  approved*: bool
  locale*: string
  isBannedUser*: bool
  groupIds*: seq[string]
  isLive*: bool
  hidden*: bool
  date*: string

