#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_feed_post_link
import model_feed_post_media_item

type UpdateFeedPostParams* = object
  ## 
  title*: Option[string]
  contentHTML*: Option[string]
  media*: Option[seq[FeedPostMediaItem]]
  links*: Option[seq[FeedPostLink]]
  tags*: Option[seq[string]]
  meta*: Option[Table[string, string]] ## Construct a type with a set of properties K of type T


# Custom JSON deserialization for UpdateFeedPostParams with custom field names
proc to*(node: JsonNode, T: typedesc[UpdateFeedPostParams]): UpdateFeedPostParams =
  result = UpdateFeedPostParams()
  if node.kind == JObject:
    if node.hasKey("title") and node["title"].kind != JNull:
      result.title = some(to(node["title"], typeof(result.title.get())))
    if node.hasKey("contentHTML") and node["contentHTML"].kind != JNull:
      result.contentHTML = some(to(node["contentHTML"], typeof(result.contentHTML.get())))
    if node.hasKey("media") and node["media"].kind != JNull:
      result.media = some(to(node["media"], typeof(result.media.get())))
    if node.hasKey("links") and node["links"].kind != JNull:
      result.links = some(to(node["links"], typeof(result.links.get())))
    if node.hasKey("tags") and node["tags"].kind != JNull:
      result.tags = some(to(node["tags"], typeof(result.tags.get())))
    if node.hasKey("meta") and node["meta"].kind != JNull:
      result.meta = some(to(node["meta"], typeof(result.meta.get())))

# Custom JSON serialization for UpdateFeedPostParams with custom field names
proc `%`*(obj: UpdateFeedPostParams): JsonNode =
  result = newJObject()
  if obj.title.isSome():
    result["title"] = %obj.title.get()
  if obj.contentHTML.isSome():
    result["contentHTML"] = %obj.contentHTML.get()
  if obj.media.isSome():
    result["media"] = %obj.media.get()
  if obj.links.isSome():
    result["links"] = %obj.links.get()
  if obj.tags.isSome():
    result["tags"] = %obj.tags.get()
  if obj.meta.isSome():
    result["meta"] = %obj.meta.get()

