#
# fastcomments
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 0.0.0
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables
import marshal
import options

import model_api_error
import model_api_status
import model_custom_config_parameters
import model_get_moderators_response
import model_moderator

# AnyOf type
type GetModeratorsResponse1Kind* {.pure.} = enum
  GetModeratorsResponseVariant
  APIErrorVariant

type GetModeratorsResponse1* = object
  ## 
  case kind*: GetModeratorsResponse1Kind
  of GetModeratorsResponse1Kind.GetModeratorsResponseVariant:
    GetModeratorsResponseValue*: GetModeratorsResponse
  of GetModeratorsResponse1Kind.APIErrorVariant:
    APIErrorValue*: APIError

proc to*(node: JsonNode, T: typedesc[GetModeratorsResponse1]): GetModeratorsResponse1 =
  ## Custom deserializer for anyOf type - tries each variant
  try:
    return GetModeratorsResponse1(kind: GetModeratorsResponse1Kind.GetModeratorsResponseVariant, GetModeratorsResponseValue: to(node, GetModeratorsResponse))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as GetModeratorsResponse: ", e.msg
  try:
    return GetModeratorsResponse1(kind: GetModeratorsResponse1Kind.APIErrorVariant, APIErrorValue: to(node, APIError))
  except Exception as e:
    when defined(debug):
      echo "Failed to deserialize as APIError: ", e.msg
  raise newException(ValueError, "Unable to deserialize into any variant of GetModeratorsResponse1. JSON: " & $node)

